### ISSUE TITLE
Nodes which are trivially capable of operating on non-CUDA devices (most of them) should use comfy's default torch device

### ISSUE THREAD

**Issue by NeedsMoar** [Fannovel16/ComfyUI-Frame-Interpolation#1]
Currently this node pack hard fails on DirectML (and anything else) because of several unchecked converts to CUDA types and the nodes that use CUPY without wrapping it in availability checks.  Since ComfyUI itself is compatible with other compute devices it should probably gracefully disable the nodes that you don't feel like converting (one has a bunch of inlined CUDA so I can see not dealing with that mess), make the ones that are already wrapped use Comfy's specified device so they don't fall back to CPU when not needed, and fix the few instances where there's an unchecked conversion to a cuda type to use a checked wrapper similar to the rest.  There shouldn't be a ton of changes needed but Python isn't a language I'll write in.

**Comment by Fannovel16** [comment]
I'll include a native PyTorch implementation of softsplatting which is the thing written in CuPy. But it'll be way slower than CuPy one.

I hope someone can compile softsplatting to ROCM and DirectML if possible.

**Comment by NeedsMoar** [comment]
ROCM is the easy one...  https://github.com/ROCmSoftwarePlatform/hipify_torch or the clang-based hipify project which can perform validation of code will just convert cuda calls over to the optimized HIP versions.  I'm pretty sure that happens automatically once torch is built with ROCM support.  Windows is still waiting on MIOpen for that AFAIK.  

I wouldn't bother with DirectML at all, ROCM is replacing it for AMD, Intel already has their own libraries and a torch backend integrated, there's no reason to use it at all on CUDA devices,  and it's not really meant to be called from python.   The Pydirectml library that's the "native" interface to it rather than a hackish torch backend has to be built from source on github and the CMakeLists needs to be patched to turn off -WX or it won't build as it is now.  

I'm fine with a slow CPU version (although a lot of these models run faster than I'd have thought on a 32/64 core 5975WX TR Pro) until the good options are in place, just so long as the extension isn't erroring on load in the meantime.   :D
