### ISSUE TITLE
Not installing properly with ComfyUI Manager or Direct installation

### ISSUE THREAD

**Issue by ZepridoArt** [Fannovel16/ComfyUI-Frame-Interpolation#10]
When loading the graph, the following node types were not found: 

    RIFE VFI

None of the nodes appear in active available custom nodes list, but the folder with all the assets are in the proper custom nodes folder. Uninstalling and reinstalling the custom node does not work.

**Comment by ZepridoArt** [comment]
I'm going through the data for the build of the launch of comfy, and it says
ModuleNotFoundError: No module named 'cupy'

**Comment by GastonSan79** [comment]
Same here, also it doesn't detect my nvidia gpu ("Unable to detect NVIDIA CUDA or AMD ROCm installation.") before the error.

**Comment by Fannovel16** [comment]
Fixed at https://github.com/Fannovel16/ComfyUI-Frame-Interpolation/commit/1463387efea20a01e33c04b0702f03febc73186b

**Comment by ZepridoArt** [comment]
"C:\Users\Jess\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\models\ops\cupy_ops\utils.py", line 1, in <module>
    import cupy
ModuleNotFoundError: No module named 'cupy'

Cannot import C:\Users\Jess\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation module for custom nodes: No module named 'cupy'
Traceback (most recent call last):
  File "C:\Users\Jess\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\nodes.py", line 1734, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Jess\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation-main\__init__.py", line 9, in <module>
    from models.gmfss_fortuna import GMFSS_Fortuna_VFI
  File "C:\Users\Jess\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation-main\models\gmfss_fortuna\__init__.py", line 7, in <module>
    from .GMFSS_Fortuna_arch import Model as GMFSS
  File "C:\Users\Jess\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation-main\models\gmfss_fortuna\GMFSS_Fortuna_arch.py", line 29, in <module>
    from models.ops import softsplat
  File "C:\Users\Jess\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation-main\models\ops\__init__.py", line 21, in <module>
    from .cupy_ops import softsplat, ModuleSoftsplat, FunctionSoftsplat, softsplat_func, costvol_func, sepconv_func, init, batch_edt
  File "C:\Users\Jess\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation-main\models\ops\cupy_ops\__init__.py", line 1, in <module>
    from .costvol import *
  File "C:\Users\Jess\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation-main\models\ops\cupy_ops\costvol.py", line 1, in <module>
    from .utils import cuda_kernel, cuda_launch, cuda_int32
  File "C:\Users\Jess\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation-main\models\ops\cupy_ops\utils.py", line 1, in <module>
    import cupy
ModuleNotFoundError: No module named 'cupy'

**Comment by ZepridoArt** [comment]
I ran install.bat it says that cupy is installed. Does this have something to do with the fact I'm using Stability Matrix?

**Comment by darrynGit** [comment]
I'm still having trouble installing. Have tried to install through ComfyUI Manager and direct using install.bat

Microsoft Windows [Version 10.0.22621.2283]
(c) Microsoft Corporation. All rights reserved.

C:\Users\darry\Documents\StableDiffusion\ComfyUI_Portable\ComfyUI\custom_nodes>git clone https://github.com/Fannovel16/ComfyUI-Frame-Interpolation
Cloning into 'ComfyUI-Frame-Interpolation'...
remote: Enumerating objects: 665, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (10/10), done.
Receiving objects: 100% (665/665), 43.57 MiB | 6.32 MiB/s, done.

Resolving deltas: 100% (362/362), done.

C:\Users\darry\Documents\StableDiffusion\ComfyUI_Portable\ComfyUI\custom_nodes>cd ComfyUI-Frame-Interpolation

C:\Users\darry\Documents\StableDiffusion\ComfyUI_Portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation>install.bat
Installing ComfyUI Frame Interpolation..
Installing with ComfyUI Portable
Installing torch...
Requirement already satisfied: torch in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (2.0.1+cu118)
Requirement already satisfied: filelock in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from torch) (3.12.2)
Requirement already satisfied: typing-extensions in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from torch) (4.7.1)
Requirement already satisfied: sympy in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from torch) (1.12)
Requirement already satisfied: networkx in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from torch) (3.1)
Requirement already satisfied: jinja2 in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from torch) (3.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from jinja2->torch) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from sympy->torch) (1.3.0)
DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
Installing numpy...
Requirement already satisfied: numpy in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (1.23.5)
DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
Installing einops...
Requirement already satisfied: einops in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (0.6.1)
DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
Installing opencv-contrib-python...
Requirement already satisfied: opencv-contrib-python in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (4.8.1.78)
Requirement already satisfied: numpy>=1.21.2 in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from opencv-contrib-python) (1.23.5)
DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
Installing kornia...
Requirement already satisfied: kornia in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (0.7.0)
Requirement already satisfied: packaging in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from kornia) (23.1)
Requirement already satisfied: torch>=1.9.1 in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from kornia) (2.0.1+cu118)
Requirement already satisfied: filelock in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from torch>=1.9.1->kornia) (3.12.2)
Requirement already satisfied: typing-extensions in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from torch>=1.9.1->kornia) (4.7.1)
Requirement already satisfied: sympy in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from torch>=1.9.1->kornia) (1.12)
Requirement already satisfied: networkx in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from torch>=1.9.1->kornia) (3.1)
Requirement already satisfied: jinja2 in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from torch>=1.9.1->kornia) (3.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from jinja2->torch>=1.9.1->kornia) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from sympy->torch>=1.9.1->kornia) (1.3.0)
DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
Installing scipy...
Requirement already satisfied: scipy in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (1.11.2)
Requirement already satisfied: numpy<1.28.0,>=1.21.6 in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from scipy) (1.23.5)
DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
Installing Pillow...
Requirement already satisfied: Pillow in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (9.5.0)
DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
Installing torchvision...
Requirement already satisfied: torchvision in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (0.15.2+cu118)
Requirement already satisfied: numpy in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from torchvision) (1.23.5)
Requirement already satisfied: requests in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from torchvision) (2.31.0)
Requirement already satisfied: torch==2.0.1 in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from torchvision) (2.0.1+cu118)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from torchvision) (9.5.0)
Requirement already satisfied: filelock in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from torch==2.0.1->torchvision) (3.12.2)
Requirement already satisfied: typing-extensions in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from torch==2.0.1->torchvision) (4.7.1)
Requirement already satisfied: sympy in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from torch==2.0.1->torchvision) (1.12)
Requirement already satisfied: networkx in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from torch==2.0.1->torchvision) (3.1)
Requirement already satisfied: jinja2 in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from torch==2.0.1->torchvision) (3.1.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from requests->torchvision) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from requests->torchvision) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from requests->torchvision) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from requests->torchvision) (2023.7.22)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from jinja2->torch==2.0.1->torchvision) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from sympy->torch==2.0.1->torchvision) (1.3.0)
DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
Installing tqdm...
Requirement already satisfied: tqdm in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (4.66.1)
Requirement already satisfied: colorama in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from tqdm) (0.4.6)
DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
Installing timm==0.6.13...
Requirement already satisfied: timm==0.6.13 in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (0.6.13)
Requirement already satisfied: torch>=1.7 in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from timm==0.6.13) (2.0.1+cu118)
Requirement already satisfied: torchvision in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from timm==0.6.13) (0.15.2+cu118)
Requirement already satisfied: pyyaml in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from timm==0.6.13) (6.0.1)
Requirement already satisfied: huggingface-hub in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from timm==0.6.13) (0.16.4)
Requirement already satisfied: filelock in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from torch>=1.7->timm==0.6.13) (3.12.2)
Requirement already satisfied: typing-extensions in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from torch>=1.7->timm==0.6.13) (4.7.1)
Requirement already satisfied: sympy in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from torch>=1.7->timm==0.6.13) (1.12)
Requirement already satisfied: networkx in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from torch>=1.7->timm==0.6.13) (3.1)
Requirement already satisfied: jinja2 in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from torch>=1.7->timm==0.6.13) (3.1.2)
Requirement already satisfied: fsspec in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from huggingface-hub->timm==0.6.13) (2023.6.0)
Requirement already satisfied: requests in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from huggingface-hub->timm==0.6.13) (2.31.0)
Requirement already satisfied: tqdm>=4.42.1 in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from huggingface-hub->timm==0.6.13) (4.66.1)
Requirement already satisfied: packaging>=20.9 in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from huggingface-hub->timm==0.6.13) (23.1)
Requirement already satisfied: numpy in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from torchvision->timm==0.6.13) (1.23.5)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from torchvision->timm==0.6.13) (9.5.0)
Requirement already satisfied: colorama in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from tqdm>=4.42.1->huggingface-hub->timm==0.6.13) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from jinja2->torch>=1.7->timm==0.6.13) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from requests->huggingface-hub->timm==0.6.13) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from requests->huggingface-hub->timm==0.6.13) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from requests->huggingface-hub->timm==0.6.13) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from requests->huggingface-hub->timm==0.6.13) (2023.7.22)
Requirement already satisfied: mpmath>=0.19 in c:\users\darry\documents\stablediffusion\comfyui_portable\python_embeded\lib\site-packages (from sympy->torch>=1.7->timm==0.6.13) (1.3.0)
DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
Checking cupy...
Uninstall cupy if existed...
WARNING: Skipping cupy-wheel as it is not installed.
WARNING: Skipping cupy-cuda102 as it is not installed.
WARNING: Skipping cupy-cuda110 as it is not installed.
WARNING: Skipping cupy-cuda111 as it is not installed.
WARNING: Skipping cupy-cuda11x as it is not installed.
WARNING: Skipping cupy-cuda12x as it is not installed.
Installing cupy...
Collecting cupy-wheel
  Using cached cupy-wheel-12.2.0.tar.gz (2.9 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      C:\Users\darry\AppData\Local\Temp\pip-install-fhswxt33\cupy-wheel_5b962796cfa24c6d85391b4dd99f84e9\setup.py:2: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
        import pkg_resources
      [cupy-wheel] CUDA_PATH is not set.cupy-wheel may not be able to discover NVRTC to probe version
      [cupy-wheel] Trying to detect CUDA version from libraries: ['nvrtc64_120_0.dll', 'nvrtc64_112_0.dll', 'nvrtc64_111_0.dll', 'nvrtc64_110_0.dll', 'nvrtc64_102_0.dll']
      [cupy-wheel] Looking for library: nvrtc64_120_0.dll
      [cupy-wheel] Failed to open nvrtc64_120_0.dll: Could not find module 'nvrtc64_120_0.dll' (or one of its dependencies). Try using the full path with constructor syntax.
      [cupy-wheel] Looking for library: nvrtc64_112_0.dll
      [cupy-wheel] Failed to open nvrtc64_112_0.dll: Could not find module 'nvrtc64_112_0.dll' (or one of its dependencies). Try using the full path with constructor syntax.
      [cupy-wheel] Looking for library: nvrtc64_111_0.dll
      [cupy-wheel] Failed to open nvrtc64_111_0.dll: Could not find module 'nvrtc64_111_0.dll' (or one of its dependencies). Try using the full path with constructor syntax.
      [cupy-wheel] Looking for library: nvrtc64_110_0.dll
      [cupy-wheel] Failed to open nvrtc64_110_0.dll: Could not find module 'nvrtc64_110_0.dll' (or one of its dependencies). Try using the full path with constructor syntax.
      [cupy-wheel] Looking for library: nvrtc64_102_0.dll
      [cupy-wheel] Failed to open nvrtc64_102_0.dll: Could not find module 'nvrtc64_102_0.dll' (or one of its dependencies). Try using the full path with constructor syntax.
      [cupy-wheel] No more candidate library to find
      [cupy-wheel] ROCm detection unsupported on platform: win32
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\darry\AppData\Local\Temp\pip-install-fhswxt33\cupy-wheel_5b962796cfa24c6d85391b4dd99f84e9\setup.py", line 285, in <module>
          main()
        File "C:\Users\darry\AppData\Local\Temp\pip-install-fhswxt33\cupy-wheel_5b962796cfa24c6d85391b4dd99f84e9\setup.py", line 269, in main
          package = infer_best_package()
        File "C:\Users\darry\AppData\Local\Temp\pip-install-fhswxt33\cupy-wheel_5b962796cfa24c6d85391b4dd99f84e9\setup.py", line 259, in infer_best_package
          raise AutoDetectionFailed(
      __main__.AutoDetectionFailed:
      ============================================================
      Unable to detect NVIDIA CUDA or AMD ROCm installation.
      ============================================================

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Press any key to continue . . .
