### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by trashie65** [Fannovel16/ComfyUI-Frame-Interpolation#12]
Installed via comfy manager

tried to install.bat, get this error below have nodes red in the workflow tried install missing nodes all points to custom node pack.

Installing ComfyUI Frame Interpolation..
Installing with ComfyUI Portable
Installing torch...
Requirement already satisfied: torch in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (2.0.1+cu118)
Requirement already satisfied: filelock in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from torch) (3.10.0)
Requirement already satisfied: typing-extensions in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from torch) (4.5.0)
Requirement already satisfied: sympy in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from torch) (1.11.1)
Requirement already satisfied: networkx in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from torch) (3.0)
Requirement already satisfied: jinja2 in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from torch) (3.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from jinja2->torch) (2.1.2)
Requirement already satisfied: mpmath>=0.19 in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from sympy->torch) (1.3.0)

[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\python.exe -m pip install --upgrade pip
Installing numpy...
Requirement already satisfied: numpy in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (1.23.5)

[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\python.exe -m pip install --upgrade pip
Installing einops...
Requirement already satisfied: einops in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (0.6.1)

[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\python.exe -m pip install --upgrade pip
Installing opencv-contrib-python...
Requirement already satisfied: opencv-contrib-python in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (4.7.0.72)
Requirement already satisfied: numpy>=1.21.2 in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from opencv-contrib-python) (1.23.5)

[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\python.exe -m pip install --upgrade pip
Installing kornia...
Requirement already satisfied: kornia in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (0.7.0)
Requirement already satisfied: packaging in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from kornia) (23.0)
Requirement already satisfied: torch>=1.9.1 in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from kornia) (2.0.1+cu118)
Requirement already satisfied: filelock in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.9.1->kornia) (3.10.0)
Requirement already satisfied: typing-extensions in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.9.1->kornia) (4.5.0)
Requirement already satisfied: sympy in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.9.1->kornia) (1.11.1)
Requirement already satisfied: networkx in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.9.1->kornia) (3.0)
Requirement already satisfied: jinja2 in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.9.1->kornia) (3.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from jinja2->torch>=1.9.1->kornia) (2.1.2)
Requirement already satisfied: mpmath>=0.19 in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from sympy->torch>=1.9.1->kornia) (1.3.0)

[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\python.exe -m pip install --upgrade pip
Installing scipy...
Requirement already satisfied: scipy in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (1.10.1)
Requirement already satisfied: numpy<1.27.0,>=1.19.5 in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from scipy) (1.23.5)

[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\python.exe -m pip install --upgrade pip
Installing Pillow...
Requirement already satisfied: Pillow in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (9.4.0)

[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\python.exe -m pip install --upgrade pip
Installing torchvision...
Requirement already satisfied: torchvision in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (0.15.2+cu118)
Requirement already satisfied: numpy in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from torchvision) (1.23.5)
Requirement already satisfied: requests in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from torchvision) (2.31.0)
Requirement already satisfied: torch==2.0.1 in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from torchvision) (2.0.1+cu118)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from torchvision) (9.4.0)
Requirement already satisfied: filelock in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from torch==2.0.1->torchvision) (3.10.0)
Requirement already satisfied: typing-extensions in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from torch==2.0.1->torchvision) (4.5.0)
Requirement already satisfied: sympy in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from torch==2.0.1->torchvision) (1.11.1)
Requirement already satisfied: networkx in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from torch==2.0.1->torchvision) (3.0)
Requirement already satisfied: jinja2 in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from torch==2.0.1->torchvision) (3.1.2)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->torchvision) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->torchvision) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->torchvision) (2.0.5)
Requirement already satisfied: certifi>=2017.4.17 in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->torchvision) (2022.12.7)
Requirement already satisfied: MarkupSafe>=2.0 in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from jinja2->torch==2.0.1->torchvision) (2.1.2)
Requirement already satisfied: mpmath>=0.19 in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from sympy->torch==2.0.1->torchvision) (1.3.0)

[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\python.exe -m pip install --upgrade pip
Installing tqdm...
Requirement already satisfied: tqdm in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (4.65.0)
Requirement already satisfied: colorama in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from tqdm) (0.4.6)

[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\python.exe -m pip install --upgrade pip
Installing timm==0.6.13...
Requirement already satisfied: timm==0.6.13 in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (0.6.13)
Requirement already satisfied: torch>=1.7 in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from timm==0.6.13) (2.0.1+cu118)
Requirement already satisfied: torchvision in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from timm==0.6.13) (0.15.2+cu118)
Requirement already satisfied: pyyaml in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from timm==0.6.13) (6.0)
Requirement already satisfied: huggingface-hub in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from timm==0.6.13) (0.17.3)
Requirement already satisfied: filelock in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.7->timm==0.6.13) (3.10.0)
Requirement already satisfied: typing-extensions in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.7->timm==0.6.13) (4.5.0)
Requirement already satisfied: sympy in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.7->timm==0.6.13) (1.11.1)
Requirement already satisfied: networkx in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.7->timm==0.6.13) (3.0)
Requirement already satisfied: jinja2 in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.7->timm==0.6.13) (3.1.2)
Requirement already satisfied: fsspec in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from huggingface-hub->timm==0.6.13) (2023.3.0)
Requirement already satisfied: requests in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from huggingface-hub->timm==0.6.13) (2.31.0)
Requirement already satisfied: tqdm>=4.42.1 in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from huggingface-hub->timm==0.6.13) (4.65.0)
Requirement already satisfied: packaging>=20.9 in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from huggingface-hub->timm==0.6.13) (23.0)
Requirement already satisfied: numpy in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from torchvision->timm==0.6.13) (1.23.5)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from torchvision->timm==0.6.13) (9.4.0)
Requirement already satisfied: colorama in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from tqdm>=4.42.1->huggingface-hub->timm==0.6.13) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from jinja2->torch>=1.7->timm==0.6.13) (2.1.2)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->huggingface-hub->timm==0.6.13) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->huggingface-hub->timm==0.6.13) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->huggingface-hub->timm==0.6.13) (2.0.5)
Requirement already satisfied: certifi>=2017.4.17 in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->huggingface-hub->timm==0.6.13) (2022.12.7)
Requirement already satisfied: mpmath>=0.19 in d:\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages (from sympy->torch>=1.7->timm==0.6.13) (1.3.0)

[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\python.exe -m pip install --upgrade pip
Checking cupy...
Uninstall cupy if existed...
WARNING: Skipping cupy-wheel as it is not installed.
WARNING: Skipping cupy-cuda102 as it is not installed.
WARNING: Skipping cupy-cuda110 as it is not installed.
WARNING: Skipping cupy-cuda111 as it is not installed.
WARNING: Skipping cupy-cuda11x as it is not installed.
WARNING: Skipping cupy-cuda12x as it is not installed.
Installing cupy...
Collecting cupy-wheel
  Using cached cupy-wheel-12.2.0.tar.gz (2.9 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      [cupy-wheel] CUDA_PATH is not set.cupy-wheel may not be able to discover NVRTC to probe version
      [cupy-wheel] Trying to detect CUDA version from libraries: ['nvrtc64_120_0.dll', 'nvrtc64_112_0.dll', 'nvrtc64_111_0.dll', 'nvrtc64_110_0.dll', 'nvrtc64_102_0.dll']
      [cupy-wheel] Looking for library: nvrtc64_120_0.dll
      [cupy-wheel] Failed to open nvrtc64_120_0.dll: Could not find module 'nvrtc64_120_0.dll' (or one of its dependencies). Try using the full path with constructor syntax.
      [cupy-wheel] Looking for library: nvrtc64_112_0.dll
      [cupy-wheel] Failed to open nvrtc64_112_0.dll: Could not find module 'nvrtc64_112_0.dll' (or one of its dependencies). Try using the full path with constructor syntax.
      [cupy-wheel] Looking for library: nvrtc64_111_0.dll
      [cupy-wheel] Failed to open nvrtc64_111_0.dll: Could not find module 'nvrtc64_111_0.dll' (or one of its dependencies). Try using the full path with constructor syntax.
      [cupy-wheel] Looking for library: nvrtc64_110_0.dll
      [cupy-wheel] Failed to open nvrtc64_110_0.dll: Could not find module 'nvrtc64_110_0.dll' (or one of its dependencies). Try using the full path with constructor syntax.
      [cupy-wheel] Looking for library: nvrtc64_102_0.dll
      [cupy-wheel] Failed to open nvrtc64_102_0.dll: Could not find module 'nvrtc64_102_0.dll' (or one of its dependencies). Try using the full path with constructor syntax.
      [cupy-wheel] No more candidate library to find
      [cupy-wheel] ROCm detection unsupported on platform: win32
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\USER\AppData\Local\Temp\pip-install-_x17ekon\cupy-wheel_59c969eaba2840e7a3f1283ab365374e\setup.py", line 285, in <module>
          main()
        File "C:\Users\USER\AppData\Local\Temp\pip-install-_x17ekon\cupy-wheel_59c969eaba2840e7a3f1283ab365374e\setup.py", line 269, in main
          package = infer_best_package()
        File "C:\Users\USER\AppData\Local\Temp\pip-install-_x17ekon\cupy-wheel_59c969eaba2840e7a3f1283ab365374e\setup.py", line 259, in infer_best_package
          raise AutoDetectionFailed(
      __main__.AutoDetectionFailed:
      ============================================================
      Unable to detect NVIDIA CUDA or AMD ROCm installation.
      ============================================================

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\python.exe -m pip install --upgrade pip
Press any key to continue . . .

**Comment by featherice** [comment]
+1

**Comment by FigittyFau** [comment]
The exact same error for me as well

**Comment by Chase0x** [comment]
+1

**Comment by aleksej622** [comment]
@Fannovel16 , the last update seems to have fixed the probem. Thanks a lot man!!

**Comment by FigittyFau** [comment]
Works here as well, thank you for your time!
