### ISSUE TITLE
[feature request] add support for looping sequences

### ISSUE THREAD

**Issue by dmarx** [Fannovel16/ComfyUI-Frame-Interpolation#14]
techniques like animatediff let us create looping sequences of frames. when these frames are passed through VFI, a "jerk" results at the loop point because the node doesn't know to interpolate between the last and first frames. demonstration: https://twitter.com/DigThatData/status/1712292557441671223

suggested fix: add a "video_is_loop" toggle (or something like that) that allows the user to indicate to the VFI node that it should  concatenate the first frame to the end before interpolating and pop it off before returning the output.

**Comment by Fannovel16** [comment]
@dmarx You can use _Make Interpolation State List_ with is_skip_list=True to indicate which pairs should be skipped. Assuming we have a 4 frames video:
0 - 1 - 2 - 3
=> Interpolation pairs: (0, 1) (1, 2) (2, 3) (3, 4)
If you want to skip pair (1, 2), (2, 3), write `1, 2` to the state list

**Comment by dmarx** [comment]
can you share a workflow demonstrating how to use the "make interpolation state" node? also, i don't want to skip anything, the problem is that I need to _add_ the pair (3,0). if there's a way i can extract the first and last frames, interpolate between them on their own, and concatenate them back into the video it'll be a bit of work but it'll solve the issue, i just don't know how to use comfyui to do that. guessing something in WAS-NS is what i need for that?

**Comment by dmarx** [comment]
maybe i can add an additional interpolation step and pass in a "state list" of (-1,0)? is that how the "state" thing works? it's just the frame ids i want interpolated?

**Comment by Fannovel16** [comment]
@dmarx Oh so you want to set a different multiplier at the loop point to smooth the transition? You can use ImageSelector from https://github.com/SLAPaper/ComfyUI-Image-Selector to specify which frames should be extracted (1-based indexing) and ImageBatchJoin from https://github.com/Nourepide/ComfyUI-Allor to join multiple batches into one.0

**Comment by dmarx** [comment]
all i want is for it to respect that the sequence is a loop. i don't want a different multiplier, i just want the same interpolation that happens between every other frame in the video to also happen between the last frame and first frame. as far as i can tell, there is no simple way to do this in your suite currently and I think it is an option you should offer, considering the alternative seems to be:

1. add three nodes to select the last and first frames to create a two-image batch for interpolation
2. add an interpolation node to create the missing frames
3. add another (multiple?) selector node to select only the new frames and throw away the first and last from the new batch
4. add a batch merge node to join the "bridge" frames onto the rest of the interpolation

that's at least six additional nodes just to interpolate between a single pair of frames that was missed by your processor. i think this is a useful enough feature that it makes sense to add it as an option in your suite, where it would also be much simpler to implement than in the node UI:

1. user activates a boolean toggle to set a variable to True
2. When True, you copy the first frame on to the end of the sequence before interpolating and remove that extra frame before returning the results. fin.

**Comment by dmarx** [comment]
...ok, maybe i can do the "node" version of the implementation i suggested with like three nodes maybe... still, it's a lot of hoops to jump through just to get it to maintain the smooth looping it was already doing before putting it through VFI

**Comment by dmarx** [comment]
got it working with three extra nodes, here's a workflow to make it concrete precisely what i'm trying to do
![workflow (1)](https://github.com/Fannovel16/ComfyUI-Frame-Interpolation/assets/1466881/72186e5f-9fd5-40f2-9bb5-fef5b4dfa103)

**Comment by SeanBannister** [comment]
Thanks for this @dmarx its my first day using ComfyUI and this was exactly what I needed.

I've noticed one downside to this method. If you're creating loops that are in time with music this adds extra frames to the end of the loop causing it to be out of time.

To fix this I think I could just "Remove every Nth frame" and get the loop back to the right length 🤷 not 100% sure but seems like the best method. I just haven't found a way to achieve this yet, if anyone has any tips that would be great.
