### ISSUE TITLE
Installation is failing. Can't retreive VFI FILM node.

### ISSUE THREAD

**Issue by Chase0x** [Fannovel16/ComfyUI-Frame-Interpolation#17]
![image](https://github.com/Fannovel16/ComfyUI-Frame-Interpolation/assets/103706623/6e2c603c-073f-4394-8518-2cb5f4c3a9e5)

**Comment by Chase0x** [comment]
![image](https://github.com/Fannovel16/ComfyUI-Frame-Interpolation/assets/103706623/448c18d5-146c-418f-b28a-1d9d0533e377)

**Comment by DashimakiG** [comment]
I had the same error, Windows11
but it was resolved by installing only CUDA of CUDA Toolkit 11.8.

CUDA Toolkit 11.8
https://developer.nvidia.com/cuda-11-8-0-download-archive?target_os=Windows&target_arch=x86_64&target_version=11&target_type=exe_local

**Comment by Chase0x** [comment]
> I had the same error, Windows11 but it was resolved by installing only CUDA of CUDA Toolkit 11.8. (Latest 12.2.2 is error)
> 
> CUDA Toolkit 11.8 https://developer.nvidia.com/cuda-11-8-0-download-archive?target_os=Windows&target_arch=x86_64&target_version=11&target_type=exe_local

YES THANK YOU <333333

**Comment by IanEck** [comment]
I installed 11.8 but still getting the same error. Do I need to uninstall the latest CUDA toolkit version? How do I do so?

**Comment by DashimakiG** [comment]
If there is more than one, it might be a good idea to delete them all before installing 11.8.

This is the Windows 11 environment I am currently running.
  1. Install only CUDA Toolkit 11.8
  2. Change the two lines in the following file to comments to avoid AMT_VFI startup errors.
\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\__init__.py
```
15:#from models.amt import AMT_VFI
31:#    "AMT VFI": AMT_VFI,

```
