### ISSUE TITLE
Film VFI not loading again on a fresh ComfyUi Install

### ISSUE THREAD

**Issue by dkamajix** [Fannovel16/ComfyUI-Frame-Interpolation#20]
Hello again,
Im getting the same issue, where Film VFI does not want to install.
I have a fresh copy of Comfy and that node does not want to work when I load a workflow that uses it.
You had fixed it with a new commit but on a new comfy install Im getting the same error as before.
Anyway to help me with it again? below is my code.

G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
** ComfyUI start up time: 2023-10-14 20:31:51.547468

Prestartup times for custom nodes:
   0.0 seconds: G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 16375 MB, total RAM 131015 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4080 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
Adding extra search path checkpoints G:\WORKSPACE AI\00_SD_MODELS\CHECKPOINTS
Adding extra search path configs G:\WORKSPACE AI\00_SD_MODELS\models/Stable-diffusion
Adding extra search path vae G:\WORKSPACE AI\00_SD_MODELS\VAE
Adding extra search path loras G:\WORKSPACE AI\00_SD_MODELS\LORAS
Adding extra search path loras G:\WORKSPACE AI\00_SD_MODELS\models/LyCORIS
Adding extra search path upscale_models G:\WORKSPACE AI\00_SD_MODELS\ERSGAN
Adding extra search path upscale_models G:\WORKSPACE AI\00_SD_MODELS\models/RealESRGAN
Adding extra search path upscale_models G:\WORKSPACE AI\00_SD_MODELS\models/SwinIR
Adding extra search path embeddings G:\WORKSPACE AI\00_SD_MODELS\EMBEDDINGS
Adding extra search path hypernetworks G:\WORKSPACE AI\00_SD_MODELS\models/hypernetworks
Adding extra search path controlnet G:\WORKSPACE AI\00_SD_MODELS\CONTROLNET
Using pytorch cross attention
G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\python_embeded\Lib\site-packages\cupy\_environment.py:216: UserWarning: CUDA path could not be detected. Set CUDA_PATH environment variable if CuPy fails to load.
  warnings.warn(
Traceback (most recent call last):
  File "G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\python_embeded\Lib\site-packages\cupy\__init__.py", line 17, in <module>
    from cupy import _core  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^
  File "G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\python_embeded\Lib\site-packages\cupy\_core\__init__.py", line 3, in <module>
    from cupy._core import core  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "cupy\_core\core.pyx", line 1, in init cupy._core.core
  File "G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\python_embeded\Lib\site-packages\cupy\cuda\__init__.py", line 8, in <module>
    from cupy.cuda import compiler  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\python_embeded\Lib\site-packages\cupy\cuda\compiler.py", line 13, in <module>
    from cupy.cuda import device
  File "cupy\cuda\device.pyx", line 1, in init cupy.cuda.device
ImportError: DLL load failed while importing runtime: The specified module could not be found.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1734, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\__init__.py", line 9, in <module>
    from models.gmfss_fortuna import GMFSS_Fortuna_VFI
  File "G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\models\gmfss_fortuna\__init__.py", line 7, in <module>
    from .GMFSS_Fortuna_arch import Model as GMFSS
  File "G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\models\gmfss_fortuna\GMFSS_Fortuna_arch.py", line 29, in <module>
    from models.ops import softsplat
  File "G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\models\ops\__init__.py", line 21, in <module>
    from .cupy_ops import softsplat, ModuleSoftsplat, FunctionSoftsplat, softsplat_func, costvol_func, sepconv_func, init, batch_edt, FunctionAdaCoF, ModuleCorrelation, FunctionCorrelation, _FunctionCorrelation
  File "G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\models\ops\cupy_ops\__init__.py", line 1, in <module>
    from .costvol import *
  File "G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\models\ops\cupy_ops\costvol.py", line 1, in <module>
    from .utils import cuda_kernel, cuda_launch, cuda_int32
  File "G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\models\ops\cupy_ops\utils.py", line 1, in <module>
    import cupy
  File "G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\python_embeded\Lib\site-packages\cupy\__init__.py", line 19, in <module>
    raise ImportError(f'''
ImportError:
================================================================
Failed to import CuPy.

If you installed CuPy via wheels (cupy-cudaXXX or cupy-rocm-X-X), make sure that the package matches with the version of CUDA or ROCm installed.

On Linux, you may need to set LD_LIBRARY_PATH environment variable depending on how you installed CUDA/ROCm.
On Windows, try setting CUDA_PATH environment variable.

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

CUDA Path: None
DLL dependencies:
  KERNEL32.dll -> C:\Windows\System32\KERNEL32.DLL
  MSVCP140.dll -> C:\Windows\SYSTEM32\msvcp140.dll
  VCRUNTIME140.dll -> G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\python_embeded\VCRUNTIME140.dll
  api-ms-win-crt-convert-l1-1-0.dll -> C:\Windows\System32\ucrtbase.dll
  api-ms-win-crt-environment-l1-1-0.dll -> C:\Windows\System32\ucrtbase.dll
  api-ms-win-crt-filesystem-l1-1-0.dll -> C:\Windows\System32\ucrtbase.dll
  api-ms-win-crt-heap-l1-1-0.dll -> C:\Windows\System32\ucrtbase.dll
  api-ms-win-crt-runtime-l1-1-0.dll -> C:\Windows\System32\ucrtbase.dll
  api-ms-win-crt-stdio-l1-1-0.dll -> C:\Windows\System32\ucrtbase.dll
  cuTENSOR.dll -> not found
  cublas64_11.dll -> not found
  cudart64_110.dll -> not found
  cudnn64_8.dll -> G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\lib\cudnn64_8.dll
  cufft64_10.dll -> not found
  curand64_10.dll -> G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\lib\curand64_10.dll
  cusolver64_11.dll -> G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\lib\cusolver64_11.dll
  cusparse64_11.dll -> not found
  nvcuda.dll -> C:\Windows\SYSTEM32\nvcuda.dll
  nvrtc64_112_0.dll -> not found
  python311.dll -> G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\python_embeded\python311.dll

Original error:
  ImportError: DLL load failed while importing runtime: The specified module could not be found.
================================================================

Cannot import G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation module for custom nodes:
================================================================
Failed to import CuPy.

If you installed CuPy via wheels (cupy-cudaXXX or cupy-rocm-X-X), make sure that the package matches with the version of CUDA or ROCm installed.

On Linux, you may need to set LD_LIBRARY_PATH environment variable depending on how you installed CUDA/ROCm.
On Windows, try setting CUDA_PATH environment variable.

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

CUDA Path: None
DLL dependencies:
  KERNEL32.dll -> C:\Windows\System32\KERNEL32.DLL
  MSVCP140.dll -> C:\Windows\SYSTEM32\msvcp140.dll
  VCRUNTIME140.dll -> G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\python_embeded\VCRUNTIME140.dll
  api-ms-win-crt-convert-l1-1-0.dll -> C:\Windows\System32\ucrtbase.dll
  api-ms-win-crt-environment-l1-1-0.dll -> C:\Windows\System32\ucrtbase.dll
  api-ms-win-crt-filesystem-l1-1-0.dll -> C:\Windows\System32\ucrtbase.dll
  api-ms-win-crt-heap-l1-1-0.dll -> C:\Windows\System32\ucrtbase.dll
  api-ms-win-crt-runtime-l1-1-0.dll -> C:\Windows\System32\ucrtbase.dll
  api-ms-win-crt-stdio-l1-1-0.dll -> C:\Windows\System32\ucrtbase.dll
  cuTENSOR.dll -> not found
  cublas64_11.dll -> not found
  cudart64_110.dll -> not found
  cudnn64_8.dll -> G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\lib\cudnn64_8.dll
  cufft64_10.dll -> not found
  curand64_10.dll -> G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\lib\curand64_10.dll
  cusolver64_11.dll -> G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\lib\cusolver64_11.dll
  cusparse64_11.dll -> not found
  nvcuda.dll -> C:\Windows\SYSTEM32\nvcuda.dll
  nvrtc64_112_0.dll -> not found
  python311.dll -> G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\python_embeded\python311.dll

Original error:
  ImportError: DLL load failed while importing runtime: The specified module could not be found.
================================================================

### ComfyUI Revision: 1575 [2231edec] | Released on '2023-10-14'
Registered sys.path: ['G:\\WORKSPACE AI\\02_COMFY\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\__init__.py', 'G:\\WORKSPACE AI\\02_COMFY\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_pycocotools', 'G:\\WORKSPACE AI\\02_COMFY\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_oneformer', 'G:\\WORKSPACE AI\\02_COMFY\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_mmpkg', 'G:\\WORKSPACE AI\\02_COMFY\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_midas_repo', 'G:\\WORKSPACE AI\\02_COMFY\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_detectron2', 'G:\\WORKSPACE AI\\02_COMFY\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\controlnet_aux', 'G:\\WORKSPACE AI\\02_COMFY\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src', 'G:\\WORKSPACE AI\\02_COMFY\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-Frame-Interpolation', 'G:\\WORKSPACE AI\\02_COMFY\\ComfyUI_windows_portable\\python_embeded\\Lib\\site-packages\\git\\ext\\gitdb', WindowsPath('G:/WORKSPACE AI/02_COMFY/ComfyUI_windows_portable/ComfyUI'), 'G:\\WORKSPACE AI\\02_COMFY\\ComfyUI_windows_portable\\ComfyUI\\comfy', 'G:\\WORKSPACE AI\\02_COMFY\\ComfyUI_windows_portable\\ComfyUI', 'G:\\WORKSPACE AI\\02_COMFY\\ComfyUI_windows_portable\\python_embeded\\python311.zip', 'G:\\WORKSPACE AI\\02_COMFY\\ComfyUI_windows_portable\\python_embeded', 'G:\\WORKSPACE AI\\02_COMFY\\ComfyUI_windows_portable\\python_embeded\\Lib\\site-packages', 'G:\\WORKSPACE AI\\02_COMFY\\ComfyUI_windows_portable\\python_embeded\\Lib\\site-packages\\win32', 'G:\\WORKSPACE AI\\02_COMFY\\ComfyUI_windows_portable\\python_embeded\\Lib\\site-packages\\win32\\lib', 'G:\\WORKSPACE AI\\02_COMFY\\ComfyUI_windows_portable\\python_embeded\\Lib\\site-packages\\Pythonwin', '../..']
G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py:26: UserWarning: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device (super slow)
  warnings.warn("Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device (super slow)")
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 196 nodes successfully.

        "Success is not just about making money. It's about making a difference." - Unknown

Total VRAM 16375 MB, total RAM 131015 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4080 : cudaMallocAsync
VAE dtype: torch.bfloat16

Import times for custom nodes:
   0.0 seconds: G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.0 seconds: G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\custom_nodes\ymc-node-suite-comfyui
   0.0 seconds (IMPORT FAILED): G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
   0.0 seconds: G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.3 seconds: G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.4 seconds: G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   1.3 seconds: G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: G:\WORKSPACE AI\02_COMFY\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json

**Comment by Fannovel16** [comment]
@dkamajix Can you reinstall the extension? I just pushed the fix

**Comment by dkamajix** [comment]
Hi,
that absolutely worked!
So is that something in your commits? or my system?
would love to know for next time.
Thanks for all the help!
