### ISSUE TITLE
AMT_S

### ISSUE THREAD

**Issue by RyanSHS6** [Fannovel16/ComfyUI-Frame-Interpolation#21]
Hello, I encountered an error after updating today. How can I solve this problem?
![image](https://github.com/Fannovel16/ComfyUI-Frame-Interpolation/assets/118988972/7ab8a9fc-5deb-40ae-acd9-d9d4525ca5b6)

**Comment by DashimakiG** [comment]
I also get the same error.
I was able to temporarily avoid the error by commenting out lines 15 and 31 of __init__.py.

\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\__init__.py
```
15:#from models.amt import AMT_VFI
31:#    "AMT VFI": AMT_VFI,
```

**Comment by RyanSHS6** [comment]
> I also get the same error. I was able to temporarily avoid the error by commenting out lines 15 and 31 of **init**.py.
> 
> \ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation__init__.py
> 
> ```
> 15:#from models.amt import AMT_VFI
> 31:#    "AMT VFI": AMT_VFI,
> `

it's a good idea! thanks
