### ISSUE TITLE
can't Import name 'get_ckpt_container_path' from 'utils' 

### ISSUE THREAD

**Issue by maxarch3** [Fannovel16/ComfyUI-Frame-Interpolation#24]
I have some problem with the node  STMFNet VFI.
I get error - can't Import name 'get_ckpt_container_path' from 'utils' 
utils 3.8 is instal
I use window 10, I am on portable version of comfyUi (uptodate with the manager )
workflow i use https://twitter.com/peteromallet/status/1716044441985728606

any feedback will be great if you have some advise. 
I am new with all those python library, probably the error is on my side but can't figure it out .

![ERROR_UTLIS](https://github.com/Fannovel16/ComfyUI-Frame-Interpolation/assets/149502281/6b57654e-7c75-4a0b-952c-2664b1d7ae33)

**Comment by Fannovel16** [comment]
The bug is actually from my side. Path of custom nodes are added to sys.path so there can be many possible path to utils as a global module. A temporary fix for now is to remove other custom nodes until the error disappear

**Comment by maxarch3** [comment]
As said, I am figuring out  on the go all this .
what is qualify as custom nodes? any node ?

**Comment by Fannovel16** [comment]
Fixed at https://github.com/Fannovel16/ComfyUI-Frame-Interpolation/commit/f19c7230cb883bf08a6dfb3e2099e75a51fa3318
