### ISSUE TITLE
RIFE OOM

### ISSUE THREAD

**Issue by BuffMcBigHuge** [Fannovel16/ComfyUI-Frame-Interpolation#25]
Using RIFE, I continuously get this error:

```
Error occurred when executing RIFE VFI:

Allocation on device 0 would exceed allowed memory. (out of memory)
```

Even on 24GB with 16 frames.

But when I run `python inference_video.py --fps=24 --video=${tempVideoPath} --output=${outputVideoPath}` from [ECCV2022-RIFE](https://github.com/megvii-research/ECCV2022-RIFE), with any number of frames, it runs without any issues.

**Comment by Fannovel16** [comment]
Pushed the fix (https://github.com/Fannovel16/ComfyUI-Frame-Interpolation/commit/f19c7230cb883bf08a6dfb3e2099e75a51fa3318)

**Comment by Fannovel16** [comment]
https://github.com/Fannovel16/ComfyUI-Frame-Interpolation/issues/23#issuecomment-1790901874

**Comment by BuffMcBigHuge** [comment]
Thank you @Fannovel16 !
