### ISSUE TITLE
Missing Frames

### ISSUE THREAD

**Issue by MarketMakerLite** [Fannovel16/ComfyUI-Frame-Interpolation#28]
Using the RIFE VFI, I'm getting one less frame than expected based on the multiplier:

![image](https://github.com/Fannovel16/ComfyUI-Frame-Interpolation/assets/83323207/0548a31a-bf6f-48d9-8f4d-f17ad6a26f19)

**Comment by Fannovel16** [comment]
@MarketMakerLite What RIFE does is that it predict the in-between of two consecutive frames. Therefore, the amount of output frames = input amount + (multiplier - 1) x (input amount - 1). In your case, 60 + (2 - 1) x (60 - 1) = 60 + 59 = 119
