### ISSUE TITLE
Error about copy

### ISSUE THREAD

**Issue by ultimatech-cn** [Fannovel16/ComfyUI-Frame-Interpolation#30]
Test the simple workflow of following
![1699615178333](https://github.com/Fannovel16/ComfyUI-Frame-Interpolation/assets/142652112/2de5015e-c2d0-4686-a002-b3fc17b8c4ba)
get error of cupy

```
>  File "E:\DEV\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\vfi_models\ops\cupy_ops\costvol.py", line 1, in <module>
>     from .utils import cuda_kernel, cuda_launch, cuda_int32
>   File "E:\DEV\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\vfi_models\ops\cupy_ops\utils.py", line 1, in <module>
>     import cupy
> ModuleNotFoundError: No module named 'cupy'
```

`..\..\..\python_embeded\python.exe -m pip install cupy`

got error

>          raise CompileError(None, pyx_file)
>       Cython.Compiler.Errors.CompileError: cupy\_core\_kernel.pyx
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for cupy
>   Running setup.py clean for cupy
> Failed to build cupy
> ERROR: Could not build wheels for cupy, which is required to install pyproject.toml-based projects

any workround for that?  I try to downgrade Cython, but failed.

**Comment by anniu1** [comment]
Check your CUDA version.

**Comment by anniu1** [comment]
> Test the simple workflow of following ![1699615178333](https://private-user-images.githubusercontent.com/142652112/282043848-2de5015e-c2d0-4686-a002-b3fc17b8c4ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NTE2NjAsIm5iZiI6MTcwMTg1MTM2MCwicGF0aCI6Ii8xNDI2NTIxMTIvMjgyMDQzODQ4LTJkZTUwMTVlLWMyZDAtNDY4Ni1hMDAyLWIzZmMxN2I4YzRiYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNlQwODI5MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NDllM2U4ZTRmMTM4Zjg2YzhjMDU3YzhkZTZkYmM3MGIzODY0ZjExZjRjOThhYzdlYmJjOWY4ZjQwZWZlMDdkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.v2D9ifvaAnevR7P4K6DlnlfNOglLO5Jkswhh-SyqOa8) get error of cupy
> 
> ```
> >  File "E:\DEV\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\vfi_models\ops\cupy_ops\costvol.py", line 1, in <module>
> >     from .utils import cuda_kernel, cuda_launch, cuda_int32
> >   File "E:\DEV\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\vfi_models\ops\cupy_ops\utils.py", line 1, in <module>
> >     import cupy
> > ModuleNotFoundError: No module named 'cupy'
> ```
> 
> `..\..\..\python_embeded\python.exe -m pip install cupy`
> 
> got error
> 
> > ```
> >      raise CompileError(None, pyx_file)
> >   Cython.Compiler.Errors.CompileError: cupy\_core\_kernel.pyx
> >   [end of output]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > note: This error originates from a subprocess, and is likely not a problem with pip.
> > ERROR: Failed building wheel for cupy
> > Running setup.py clean for cupy
> > Failed to build cupy
> > ERROR: Could not build wheels for cupy, which is required to install pyproject.toml-based projects
> 
> any workround for that? I try to downgrade Cython, but failed.

Check your CUDA version.

**Comment by Andro-Meta** [comment]
@ultimatech-cn Here's a fix that worked for me and a few others:

Head to ComfyUI\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\nvrtc_dlls
Copy
nvrtc64_112_0.dll and nvrtc-builtins64_118.dll
to
ComfyUI\python_embeded\Lib\site-packages\torch\lib

This has got STMFNet working on my computer.

**Comment by Fannovel16** [comment]
Fixed in https://github.com/Fannovel16/ComfyUI-Frame-Interpolation/commit/86b0e54be09ba34453857476ab97eb6ee9bbc03b

**Comment by ultimatech-cn** [comment]
Thanks a lot!
