### ISSUE TITLE
Open to licensing

### ISSUE THREAD

**Issue by rt2zz** [Fannovel16/ComfyUI-Frame-Interpolation#31]
Hello! I see the repo is unlicensed. Have you considered adding a license and if so which?

**Comment by Fannovel16** [comment]
Oh I forgot to put a license 😅 
I just copy code from other repo (mainly [VSGAN-tensorrt-docker](https://github.com/styler00dollar/VSGAN-tensorrt-docker)) so I choose MIT for simplicity
https://github.com/Fannovel16/ComfyUI-Frame-Interpolation/blob/main/LICENSE
