### ISSUE TITLE
Failed to import CuPy

### ISSUE THREAD

**Issue by BigBlueGX** [Fannovel16/ComfyUI-Frame-Interpolation#32]
I am having trouble with Cupy. 

Installed ComfyUI-Frame-Interpolation through ComfyUI's manager

Hit update all to make sure everything is the latest version

Tried the example below
[https://github.com/Fannovel16/ComfyUI-Frame-Interpolation/raw/main/example.png](https://github.com/Fannovel16/ComfyUI-Frame-Interpolation/raw/main/example.png)

Got an error

Terminal says
________________________________________________________________________________________
got prompt
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "D:\SD\ComfyUI_windows_portable\python_embeded\Lib\site-packages\cupy\__init__.py", line 17, in <module>
    from cupy import _core  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SD\ComfyUI_windows_portable\python_embeded\Lib\site-packages\cupy\_core\__init__.py", line 3, in <module>
    from cupy._core import core  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "cupy\_core\core.pyx", line 1, in init cupy._core.core
  File "D:\SD\ComfyUI_windows_portable\python_embeded\Lib\site-packages\cupy\cuda\__init__.py", line 8, in <module>
    from cupy.cuda import compiler  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SD\ComfyUI_windows_portable\python_embeded\Lib\site-packages\cupy\cuda\compiler.py", line 13, in <module>
    from cupy.cuda import device
  File "cupy\cuda\device.pyx", line 1, in init cupy.cuda.device
ImportError: DLL load failed while importing runtime: The specified module could not be found.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\vfi_models\gmfss_fortuna\__init__.py", line 128, in vfi
    interpolation_model = CommonModelInference(model_type=ckpt_name)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\vfi_models\gmfss_fortuna\__init__.py", line 30, in __init__
    from .GMFSS_Fortuna_arch import Model as GMFSS
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\vfi_models\gmfss_fortuna\GMFSS_Fortuna_arch.py", line 29, in <module>
    from vfi_models.ops import softsplat
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\vfi_models\ops\__init__.py", line 21, in <module>
    from .cupy_ops import softsplat, ModuleSoftsplat, FunctionSoftsplat, softsplat_func, costvol_func, sepconv_func, init, batch_edt, FunctionAdaCoF, ModuleCorrelation, FunctionCorrelation, _FunctionCorrelation
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\vfi_models\ops\cupy_ops\__init__.py", line 1, in <module>
    from .costvol import *
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\vfi_models\ops\cupy_ops\costvol.py", line 1, in <module>
    from .utils import cuda_kernel, cuda_launch, cuda_int32
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\vfi_models\ops\cupy_ops\utils.py", line 1, in <module>
    import cupy
  File "D:\SD\ComfyUI_windows_portable\python_embeded\Lib\site-packages\cupy\__init__.py", line 19, in <module>
    raise ImportError(f'''
ImportError:
================================================================
Failed to import CuPy.

If you installed CuPy via wheels (cupy-cudaXXX or cupy-rocm-X-X), make sure that the package matches with the version of CUDA or ROCm installed.

On Linux, you may need to set LD_LIBRARY_PATH environment variable depending on how you installed CUDA/ROCm.
On Windows, try setting CUDA_PATH environment variable.

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

CUDA Path: None
DLL dependencies:
  KERNEL32.dll -> C:\Windows\System32\KERNEL32.DLL
  MSVCP140.dll -> C:\Windows\SYSTEM32\msvcp140.dll
  VCRUNTIME140.dll -> D:\SD\ComfyUI_windows_portable\python_embeded\VCRUNTIME140.dll
  api-ms-win-crt-convert-l1-1-0.dll -> C:\Windows\System32\ucrtbase.dll
  api-ms-win-crt-environment-l1-1-0.dll -> C:\Windows\System32\ucrtbase.dll
  api-ms-win-crt-filesystem-l1-1-0.dll -> C:\Windows\System32\ucrtbase.dll
  api-ms-win-crt-heap-l1-1-0.dll -> C:\Windows\System32\ucrtbase.dll
  api-ms-win-crt-runtime-l1-1-0.dll -> C:\Windows\System32\ucrtbase.dll
  api-ms-win-crt-stdio-l1-1-0.dll -> C:\Windows\System32\ucrtbase.dll
  cuTENSOR.dll -> not found
  cublas64_11.dll -> not found
  cudart64_110.dll -> not found
  cudnn64_8.dll -> D:\SD\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\lib\cudnn64_8.dll
  cufft64_10.dll -> not found
  curand64_10.dll -> D:\SD\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\lib\curand64_10.dll
  cusolver64_11.dll -> D:\SD\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\lib\cusolver64_11.dll
  cusparse64_11.dll -> not found
  nvcuda.dll -> C:\Windows\SYSTEM32\nvcuda.dll
  nvrtc64_112_0.dll -> not found
  python311.dll -> D:\SD\ComfyUI_windows_portable\python_embeded\python311.dll

Original error:
  ImportError: DLL load failed while importing runtime: The specified module could not be found.
================================================================

Prompt executed in 0.04 seconds`

________________________________________________________________________________________

I then ran install.bat in the ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation directory

Here is the result in the terminal:

________________________________________________________________________________________

Installing ComfyUI Frame Interpolation..
Installing with ComfyUI Portable
Installing torch...
Requirement already satisfied: torch in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (2.1.1+cu121)
Requirement already satisfied: filelock in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torch) (3.13.1)
Requirement already satisfied: typing-extensions in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torch) (4.8.0)
Requirement already satisfied: sympy in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torch) (1.12)
Requirement already satisfied: networkx in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torch) (3.2.1)
Requirement already satisfied: jinja2 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torch) (3.1.2)
Requirement already satisfied: fsspec in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torch) (2023.10.0)
Requirement already satisfied: MarkupSafe>=2.0 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from jinja2->torch) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from sympy->torch) (1.3.0)
Installing numpy...
Requirement already satisfied: numpy in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (1.26.2)
Installing einops...
Requirement already satisfied: einops in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (0.7.0)
Installing opencv-contrib-python...
Requirement already satisfied: opencv-contrib-python in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (4.8.1.78)
Requirement already satisfied: numpy>=1.21.2 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from opencv-contrib-python) (1.26.2)
Installing kornia...
Requirement already satisfied: kornia in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (0.7.0)
Requirement already satisfied: packaging in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from kornia) (23.2)
Requirement already satisfied: torch>=1.9.1 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from kornia) (2.1.1+cu121)
Requirement already satisfied: filelock in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.9.1->kornia) (3.13.1)
Requirement already satisfied: typing-extensions in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.9.1->kornia) (4.8.0)
Requirement already satisfied: sympy in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.9.1->kornia) (1.12)
Requirement already satisfied: networkx in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.9.1->kornia) (3.2.1)
Requirement already satisfied: jinja2 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.9.1->kornia) (3.1.2)
Requirement already satisfied: fsspec in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.9.1->kornia) (2023.10.0)
Requirement already satisfied: MarkupSafe>=2.0 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from jinja2->torch>=1.9.1->kornia) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from sympy->torch>=1.9.1->kornia) (1.3.0)
Installing scipy...
Requirement already satisfied: scipy in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (1.11.4)
Requirement already satisfied: numpy<1.28.0,>=1.21.6 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from scipy) (1.26.2)
Installing Pillow...
Requirement already satisfied: Pillow in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (9.5.0)
Installing torchvision...
Requirement already satisfied: torchvision in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (0.16.1+cu121)
Requirement already satisfied: numpy in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torchvision) (1.26.2)
Requirement already satisfied: requests in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torchvision) (2.31.0)
Requirement already satisfied: torch==2.1.1+cu121 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torchvision) (2.1.1+cu121)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torchvision) (9.5.0)
Requirement already satisfied: filelock in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torch==2.1.1+cu121->torchvision) (3.13.1)
Requirement already satisfied: typing-extensions in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torch==2.1.1+cu121->torchvision) (4.8.0)
Requirement already satisfied: sympy in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torch==2.1.1+cu121->torchvision) (1.12)
Requirement already satisfied: networkx in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torch==2.1.1+cu121->torchvision) (3.2.1)
Requirement already satisfied: jinja2 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torch==2.1.1+cu121->torchvision) (3.1.2)
Requirement already satisfied: fsspec in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torch==2.1.1+cu121->torchvision) (2023.10.0)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->torchvision) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->torchvision) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->torchvision) (1.26.18)
Requirement already satisfied: certifi>=2017.4.17 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->torchvision) (2023.11.17)
Requirement already satisfied: MarkupSafe>=2.0 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from jinja2->torch==2.1.1+cu121->torchvision) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from sympy->torch==2.1.1+cu121->torchvision) (1.3.0)
Installing tqdm...
Requirement already satisfied: tqdm in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (4.66.1)
Requirement already satisfied: colorama in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from tqdm) (0.4.6)
Installing timm==0.6.13...
Requirement already satisfied: timm==0.6.13 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (0.6.13)
Requirement already satisfied: torch>=1.7 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from timm==0.6.13) (2.1.1+cu121)
Requirement already satisfied: torchvision in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from timm==0.6.13) (0.16.1+cu121)
Requirement already satisfied: pyyaml in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from timm==0.6.13) (6.0.1)
Requirement already satisfied: huggingface-hub in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from timm==0.6.13) (0.19.4)
Requirement already satisfied: filelock in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.7->timm==0.6.13) (3.13.1)
Requirement already satisfied: typing-extensions in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.7->timm==0.6.13) (4.8.0)
Requirement already satisfied: sympy in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.7->timm==0.6.13) (1.12)
Requirement already satisfied: networkx in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.7->timm==0.6.13) (3.2.1)
Requirement already satisfied: jinja2 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.7->timm==0.6.13) (3.1.2)
Requirement already satisfied: fsspec in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.7->timm==0.6.13) (2023.10.0)
Requirement already satisfied: requests in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from huggingface-hub->timm==0.6.13) (2.31.0)
Requirement already satisfied: tqdm>=4.42.1 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from huggingface-hub->timm==0.6.13) (4.66.1)
Requirement already satisfied: packaging>=20.9 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from huggingface-hub->timm==0.6.13) (23.2)
Requirement already satisfied: numpy in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torchvision->timm==0.6.13) (1.26.2)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torchvision->timm==0.6.13) (9.5.0)
Requirement already satisfied: colorama in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from tqdm>=4.42.1->huggingface-hub->timm==0.6.13) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from jinja2->torch>=1.7->timm==0.6.13) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->huggingface-hub->timm==0.6.13) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->huggingface-hub->timm==0.6.13) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->huggingface-hub->timm==0.6.13) (1.26.18)
Requirement already satisfied: certifi>=2017.4.17 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->huggingface-hub->timm==0.6.13) (2023.11.17)
Requirement already satisfied: mpmath>=0.19 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from sympy->torch>=1.7->timm==0.6.13) (1.3.0)
Checking cupy...
Uninstall cupy if existed...
WARNING: Skipping cupy-wheel as it is not installed.
WARNING: Skipping cupy-cuda102 as it is not installed.
WARNING: Skipping cupy-cuda110 as it is not installed.
WARNING: Skipping cupy-cuda111 as it is not installed.
Found existing installation: cupy-cuda11x 12.3.0
Uninstalling cupy-cuda11x-12.3.0:
  Successfully uninstalled cupy-cuda11x-12.3.0
WARNING: Skipping cupy-cuda12x as it is not installed.
Installing cupy...
Collecting cupy-cuda11x
  Using cached cupy_cuda11x-12.3.0-cp311-cp311-win_amd64.whl.metadata (2.7 kB)
Requirement already satisfied: numpy<1.29,>=1.20 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from cupy-cuda11x) (1.26.2)
Requirement already satisfied: fastrlock>=0.5 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from cupy-cuda11x) (0.8.2)
Using cached cupy_cuda11x-12.3.0-cp311-cp311-win_amd64.whl (70.0 MB)
Installing collected packages: cupy-cuda11x
Successfully installed cupy-cuda11x-12.3.0

________________________________________________________________________________________

**Comment by BigBlueGX** [comment]
also running install.bat shows the following:
__________________________________________________

Installing ComfyUI Frame Interpolation..
Installing with ComfyUI Portable
Installing torch...
Requirement already satisfied: torch in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (2.1.1+cu121)
Requirement already satisfied: filelock in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torch)(3.13.1)
Requirement already satisfied: typing-extensions in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torch) (4.8.0)
Requirement already satisfied: sympy in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torch) (1.12)
Requirement already satisfied: networkx in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torch)(3.2.1)
Requirement already satisfied: jinja2 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torch) (3.1.2)
Requirement already satisfied: fsspec in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torch) (2023.10.0)
Requirement already satisfied: MarkupSafe>=2.0 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (fromjinja2->torch) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from sympy->torch) (1.3.0)
Installing numpy...
Requirement already satisfied: numpy in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (1.24.4)
Installing einops...
Requirement already satisfied: einops in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (0.7.0)
Installing opencv-contrib-python...
Requirement already satisfied: opencv-contrib-python in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages(4.8.1.78)
Requirement already satisfied: numpy>=1.21.2 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from opencv-contrib-python) (1.24.4)
Installing kornia...
Requirement already satisfied: kornia in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (0.7.0)
Requirement already satisfied: packaging in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from kornia) (23.2)
Requirement already satisfied: torch>=1.9.1 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from kornia) (2.1.1+cu121)
Requirement already satisfied: filelock in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.9.1->kornia) (3.13.1)
Requirement already satisfied: typing-extensions in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.9.1->kornia) (4.8.0)
Requirement already satisfied: sympy in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.9.1->kornia) (1.12)
Requirement already satisfied: networkx in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.9.1->kornia) (3.2.1)
Requirement already satisfied: jinja2 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.9.1->kornia) (3.1.2)
Requirement already satisfied: fsspec in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.9.1->kornia) (2023.10.0)
Requirement already satisfied: MarkupSafe>=2.0 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (fromjinja2->torch>=1.9.1->kornia) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from sympy->torch>=1.9.1->kornia) (1.3.0)
Installing scipy...
Requirement already satisfied: scipy in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (1.11.4)
Requirement already satisfied: numpy<1.28.0,>=1.21.6 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages(from scipy) (1.24.4)
Installing Pillow...
Requirement already satisfied: Pillow in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (9.5.0)
Installing torchvision...
Requirement already satisfied: torchvision in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (0.16.1+cu121)
Requirement already satisfied: numpy in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torchvision) (1.24.4)
Requirement already satisfied: requests in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torchvision) (2.31.0)
Requirement already satisfied: torch==2.1.1+cu121 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torchvision) (2.1.1+cu121)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages(from torchvision) (9.5.0)
Requirement already satisfied: filelock in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torch==2.1.1+cu121->torchvision) (3.13.1)
Requirement already satisfied: typing-extensions in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torch==2.1.1+cu121->torchvision) (4.8.0)
Requirement already satisfied: sympy in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torch==2.1.1+cu121->torchvision) (1.12)
Requirement already satisfied: networkx in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torch==2.1.1+cu121->torchvision) (3.2.1)
Requirement already satisfied: jinja2 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torch==2.1.1+cu121->torchvision) (3.1.2)
Requirement already satisfied: fsspec in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torch==2.1.1+cu121->torchvision) (2023.10.0)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->torchvision) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->torchvision) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->torchvision) (1.26.18)
Requirement already satisfied: certifi>=2017.4.17 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->torchvision) (2023.11.17)
Requirement already satisfied: MarkupSafe>=2.0 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (fromjinja2->torch==2.1.1+cu121->torchvision) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from sympy->torch==2.1.1+cu121->torchvision) (1.3.0)
Installing tqdm...
Requirement already satisfied: tqdm in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (4.66.1)
Requirement already satisfied: colorama in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from tqdm) (0.4.6)
Installing timm==0.6.13...
Requirement already satisfied: timm==0.6.13 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (0.6.13)
Requirement already satisfied: torch>=1.7 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from timm==0.6.13) (2.1.1+cu121)
Requirement already satisfied: torchvision in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from timm==0.6.13) (0.16.1+cu121)
Requirement already satisfied: pyyaml in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from timm==0.6.13) (6.0.1)
Requirement already satisfied: huggingface-hub in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (fromtimm==0.6.13) (0.19.4)
Requirement already satisfied: filelock in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.7->timm==0.6.13) (3.13.1)
Requirement already satisfied: typing-extensions in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.7->timm==0.6.13) (4.8.0)
Requirement already satisfied: sympy in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.7->timm==0.6.13) (1.12)
Requirement already satisfied: networkx in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.7->timm==0.6.13) (3.2.1)
Requirement already satisfied: jinja2 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.7->timm==0.6.13) (3.1.2)
Requirement already satisfied: fsspec in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.7->timm==0.6.13) (2023.10.0)
Requirement already satisfied: requests in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from huggingface-hub->timm==0.6.13) (2.31.0)
Requirement already satisfied: tqdm>=4.42.1 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from huggingface-hub->timm==0.6.13) (4.66.1)
Requirement already satisfied: packaging>=20.9 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (fromhuggingface-hub->timm==0.6.13) (23.2)
Requirement already satisfied: numpy in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from torchvision->timm==0.6.13) (1.24.4)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages(from torchvision->timm==0.6.13) (9.5.0)
Requirement already satisfied: colorama in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from tqdm>=4.42.1->huggingface-hub->timm==0.6.13) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (fromjinja2->torch>=1.7->timm==0.6.13) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->huggingface-hub->timm==0.6.13) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->huggingface-hub->timm==0.6.13) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->huggingface-hub->timm==0.6.13) (1.26.18)
Requirement already satisfied: certifi>=2017.4.17 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->huggingface-hub->timm==0.6.13) (2023.11.17)
Requirement already satisfied: mpmath>=0.19 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from sympy->torch>=1.7->timm==0.6.13) (1.3.0)
Checking cupy...
Uninstall cupy if existed...
WARNING: Skipping cupy-wheel as it is not installed.
WARNING: Skipping cupy-cuda102 as it is not installed.
WARNING: Skipping cupy-cuda110 as it is not installed.
WARNING: Skipping cupy-cuda111 as it is not installed.
Found existing installation: cupy-cuda11x 12.3.0
Uninstalling cupy-cuda11x-12.3.0:
  Successfully uninstalled cupy-cuda11x-12.3.0
WARNING: Skipping cupy-cuda12x as it is not installed.
Installing cupy...
Collecting cupy-cuda11x
  Using cached cupy_cuda11x-12.3.0-cp311-cp311-win_amd64.whl.metadata (2.7 kB)
Requirement already satisfied: numpy<1.29,>=1.20 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from cupy-cuda11x) (1.24.4)
Requirement already satisfied: fastrlock>=0.5 in d:\sd\comfyui_windows_portable\python_embeded\lib\site-packages (from cupy-cuda11x) (0.8.2)
Using cached cupy_cuda11x-12.3.0-cp311-cp311-win_amd64.whl (70.0 MB)
Installing collected packages: cupy-cuda11x
Successfully installed cupy-cuda11x-12.3.0
Press any key to continue . . .

**Comment by traugdor** [comment]
same issue on linux.

**Comment by BigBlueGX** [comment]
I fixed the issue

I originally installed CUDA Toolkit 12.3

The plug in works only with 11.8 (https://developer.nvidia.com/cuda-11-8-0-download-archive)

I uninstalled 12.3 and installed 11.8. I then ran "install.bat" from this custom plugins dir and it worked!
