### ISSUE TITLE
[Requirements] Timm Version (Low Priority)

### ISSUE THREAD

**Issue by dnl13** [Fannovel16/ComfyUI-Frame-Interpolation#34]
I appreciate these fantastic nodes.

I have a simple question: I recently updated my comfyui and all node suites via the manager. After restarting comfyui, all requirements are installed again as usual. However, I noticed that your repository installs `timm==0.6.13`, but later in the process, `comfyui_segment_anything` removes it and installs `timm-0.9.12`.

Would it be feasible to update your nodes to the newer version of timm, or would that potentially lead to errors?

I believe `segment-anything` simply uses the latest version. Here is the `requirements.txt` of `segment-anything`:
```
segment_anything
timm
addict
yapf
```
Thank you very much.

**Comment by Fannovel16** [comment]
I removed timm in requirements as it isn't imported anywhere (https://github.com/Fannovel16/ComfyUI-Frame-Interpolation/commit/084c8f64bdcbce75e42b1bfb160a5d4f570cc0a3)
