### ISSUE TITLE
RIFE Crashing silentlty

### ISSUE THREAD

**Issue by phreax** [Fannovel16/ComfyUI-Frame-Interpolation#36]
It used to work fine, but suddenly RIFE is crashing silently after a while.
Using the latest commit with latest ComfyUI, with rife49.pth checkpoint (I tried 46, 47 as well) running on a T4 in google colab
Input has only 120 frames. 

Output is:

```
got prompt
Comfy-VFI: Clearing cache...
Comfy-VFI: Done cache clearing
Comfy-VFI: Clearing cache...
Comfy-VFI: Done cache clearing
Comfy-VFI: Clearing cache...
Comfy-VFI: Done cache clearing
Comfy-VFI: Clearing cache...
Comfy-VFI: Done cache clearing
Comfy-VFI: Clearing cache...
Comfy-VFI: Done cache clearing
Comfy-VFI: Clearing cache...
Comfy-VFI: Done cache clearing
Comfy-VFI: Clearing cache...
Comfy-VFI: Done cache clearing
Comfy-VFI: Clearing cache...
Comfy-VFI: Done cache clearing
Comfy-VFI: Clearing cache...
Comfy-VFI: Done cache clearing
Comfy-VFI: Clearing cache...
Comfy-VFI: Done cache clearing
Comfy-VFI: Clearing cache...
Comfy-VFI: Done cache clearing
^C
```

**Comment by aiXander** [comment]
Yeah having the same issue, I can see the VRAM slowly going up while RIFE is running until it crashes due to OOM. Feel like the clearing cache isnt actually working maybe?

**Comment by aiXander** [comment]
Ok, I think the problem is that the code [here](https://github.com/Fannovel16/ComfyUI-Frame-Interpolation/blob/main/vfi_utils.py#L123) only clears the gpu memory cache and not the VRAM cache. 

I think the only solution for longer videos is to save the interpolated frames to disk instead of keeping them in memory.

**Comment by aiXander** [comment]
Created a tiny pull request with some improvements:
https://github.com/Fannovel16/ComfyUI-Frame-Interpolation/pull/37
