### ISSUE TITLE
Failed to Import CuPY (FIXED)

### ISSUE THREAD

**Issue by Andro-Meta** [Fannovel16/ComfyUI-Frame-Interpolation#41]
I've been really curious to try and completely failing at getting a node from ComfyUI-Frame-Interpolation to load called STMFNet VFI. 

Here is what I've done to try to fix it myself so far.
*Removed ComfyUI-Frame-Interpolation and git cloned it
*Ran the install.bat file
*Uninstalled and Reinstalled CUDA 12.1
*Restarted my computer
*Made sure path was correct (I think it is?) in my environment variables in Windows. (The error says something about that, maybe this is what I'm doing wrong).
*Installed a completely new instance of ComfyUI
*Git Cloned from the repo
*Ran the install.bat

I'm running on Windows 11 Pro with an RTX 4090, Cuda 12.1 and Python 3.10.11

I also just updated to Python 3.11 and ran a new install of everything again to see if that would help resolve this.

Here's the error message I receive:

![STMFNet1](https://github.com/Fannovel16/ComfyUI-Frame-Interpolation/assets/146106280/10f456f0-ce67-45cc-bbcd-bc2a048fbb4e)
 

> 

Error occurred when executing STMFNet VFI:

================================================================
Failed to import CuPy.

If you installed CuPy via wheels (cupy-cudaXXX or cupy-rocm-X-X), make sure that the package matches with the version of CUDA or ROCm installed.

On Linux, you may need to set LD_LIBRARY_PATH environment variable depending on how you installed CUDA/ROCm.
On Windows, try setting CUDA_PATH environment variable.

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

CUDA Path: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1
DLL dependencies:
  KERNEL32.dll -> C:\Windows\System32\KERNEL32.DLL
  MSVCP140.dll -> C:\Windows\SYSTEM32\msvcp140.dll
  VCRUNTIME140.dll -> E:\000ComfyUI_portable_Cuda121\python_embeded\VCRUNTIME140.dll
  api-ms-win-crt-convert-l1-1-0.dll -> C:\Windows\System32\ucrtbase.dll
  api-ms-win-crt-environment-l1-1-0.dll -> C:\Windows\System32\ucrtbase.dll
  api-ms-win-crt-filesystem-l1-1-0.dll -> C:\Windows\System32\ucrtbase.dll
  api-ms-win-crt-heap-l1-1-0.dll -> C:\Windows\System32\ucrtbase.dll
  api-ms-win-crt-runtime-l1-1-0.dll -> C:\Windows\System32\ucrtbase.dll
  api-ms-win-crt-stdio-l1-1-0.dll -> C:\Windows\System32\ucrtbase.dll
  cuTENSOR.dll -> not found
  cublas64_11.dll -> not found
  cudart64_110.dll -> not found
  cudnn64_8.dll -> E:\000ComfyUI_portable_Cuda121\python_embeded\Lib\site-packages\torch\lib\cudnn64_8.dll
  cufft64_10.dll -> not found
  curand64_10.dll -> E:\000ComfyUI_portable_Cuda121\python_embeded\Lib\site-packages\torch\lib\curand64_10.dll
  cusolver64_11.dll -> E:\000ComfyUI_portable_Cuda121\python_embeded\Lib\site-packages\torch\lib\cusolver64_11.dll
  cusparse64_11.dll -> not found
  nvcuda.dll -> C:\Windows\SYSTEM32\nvcuda.dll
  nvrtc64_112_0.dll -> not found
  python311.dll -> E:\000ComfyUI_portable_Cuda121\python_embeded\python311.dll

Original error:
  ImportError: DLL load failed while importing runtime: The specified module could not be found.
================================================================

  File "E:\000ComfyUI_portable_Cuda121\ComfyUI\execution.py", line 154, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\000ComfyUI_portable_Cuda121\ComfyUI\execution.py", line 84, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\000ComfyUI_portable_Cuda121\ComfyUI\execution.py", line 77, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\000ComfyUI_portable_Cuda121\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\vfi_models\stmfnet\__init__.py", line 45, in vfi
    from .stmfnet_arch import STMFNet_Model
  File "E:\000ComfyUI_portable_Cuda121\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\vfi_models\stmfnet\stmfnet_arch.py", line 28, in 
    from vfi_models.ops import FunctionCorrelation, FunctionAdaCoF, ModuleSoftsplat
  File "E:\000ComfyUI_portable_Cuda121\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\vfi_models\ops\__init__.py", line 21, in 
    from .cupy_ops import softsplat, ModuleSoftsplat, FunctionSoftsplat, softsplat_func, costvol_func, sepconv_func, init, batch_edt, FunctionAdaCoF, ModuleCorrelation, FunctionCorrelation, _FunctionCorrelation
  File "E:\000ComfyUI_portable_Cuda121\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\vfi_models\ops\cupy_ops\__init__.py", line 1, in 
    from .costvol import *
  File "E:\000ComfyUI_portable_Cuda121\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\vfi_models\ops\cupy_ops\costvol.py", line 1, in 
    from .utils import cuda_kernel, cuda_launch, cuda_int32
  File "E:\000ComfyUI_portable_Cuda121\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\vfi_models\ops\cupy_ops\utils.py", line 1, in 
    import cupy
  File "E:\000ComfyUI_portable_Cuda121\python_embeded\Lib\site-packages\cupy\__init__.py", line 19, in 
    raise ImportError(f'''

>

**Comment by so-lost** [comment]
I have the same issue and would also love to find a solution for this error!

**Comment by Lemosine** [comment]
+1 cant figure this out also...

**Comment by iozsoo** [comment]
same here

**Comment by Andro-Meta** [comment]
@iozsoo @Lemosine @so-lost There's a pretty difficult problem to overcome with CuPY, especially when running with windows. I spent the better part of two days just focused on trying any way I could to get it to work. Fannovel16 is aware of the issue, but there's really no solution for it other than installing Linux and going that route. The quick fix I have found that works? Swap out your interpolator with FiLM or RIFE and your workflows will work.

**Comment by Andro-Meta** [comment]
@Lemosine @iozsoo @JaredTherriault Here's the fix

Head to ComfyUI\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\nvrtc_dlls 
Copy
nvrtc64_112_0.dll and nvrtc-builtins64_118.dll 
to
ComfyUI\python_embeded\Lib\site-packages\torch\lib

This has got STMFNet working on my computer.

**Comment by Fannovel16** [comment]
Fixed in https://github.com/Fannovel16/ComfyUI-Frame-Interpolation/commit/86b0e54be09ba34453857476ab97eb6ee9bbc03b

**Comment by Bladed3d** [comment]
> @Lemosine @iozsoo @JaredTherriault Here's the fix
> 
> Head to ComfyUI\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\nvrtc_dlls Copy nvrtc64_112_0.dll and nvrtc-builtins64_118.dll to ComfyUI\python_embeded\Lib\site-packages\torch\lib
> 
> This has got STMFNet working on my computer.

Did not work for me.
