### ISSUE TITLE
- Value not in list: ckpt_name: 'sudo_rife4_269.662_testV1_scale1.pth'

### ISSUE THREAD

**Issue by Mlkmengmeng** [Fannovel16/ComfyUI-Frame-Interpolation#42]
- Value not in list: ckpt_name: 'sudo_rife4_269.662_testV1_scale1.pth' not in ['rife40.pth', 'rife41.pth', 'rife42.pth', 'rife43.pth', 'rife44.pth', 'rife45.pth', 'rife46.pth', 'rife47.pth', 'rife48.pth', 'rife49.pth']

**Comment by inchinet** [comment]
Where should rife47.pth etc to place?
