### ISSUE TITLE
how to run on Mac m2, thx

### ISSUE THREAD

**Issue by hike2008** [Fannovel16/ComfyUI-Frame-Interpolation#47]
RuntimeError: MPS: Unsupported Border padding mode

I have tried the config to taichi，but error the same above

**Comment by yanhangr** [comment]
same error

ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/Users/yanhangr/program/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yanhangr/program/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yanhangr/program/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yanhangr/program/ComfyUI/custom_nodes/ComfyUI-Frame-Interpolation/vfi_models/rife/__init__.py", line 104, in vfi
    generic_frame_loop(frames, clear_cache_after_n_frames, multiplier, return_middle_frame, *args,
  File "/Users/yanhangr/program/ComfyUI/custom_nodes/ComfyUI-Frame-Interpolation/vfi_utils.py", line 167, in generic_frame_loop
    middle_frame = return_middle_frame_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yanhangr/program/ComfyUI/custom_nodes/ComfyUI-Frame-Interpolation/vfi_models/rife/__init__.py", line 98, in return_middle_frame
    return model(frame_0, frame_1, timestep, scale_list, in_fast_mode, in_ensemble)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/comfyui/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/comfyui/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yanhangr/program/ComfyUI/custom_nodes/ComfyUI-Frame-Interpolation/vfi_models/rife/rife_arch.py", line 563, in forward
    warped_img0 = warp(img0, flow[:, :2])
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yanhangr/program/ComfyUI/custom_nodes/ComfyUI-Frame-Interpolation/vfi_models/rife/rife_arch.py", line 59, in warp
    return torch.nn.functional.grid_sample(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/comfyui/lib/python3.12/site-packages/torch/nn/functional.py", line 4351, in grid_sample
    return torch.grid_sampler(input, grid, mode_enum, padding_mode_enum, align_corners)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: MPS: Unsupported Border padding mode

**Comment by Mackay031** [comment]
Just wondering if there are any Mac hacks to get Film working on a Mac? Getting a 'failed in the Torchscript interpreter' error. Thanks

**Comment by dimagrechkin** [comment]
Hey there! Same for me!

**Comment by tamler** [comment]
Same - MBP M2 Max with 64gb ram

Following this tutorial in case knowing what other nodes or settings are in use:
https://www.youtube.com/watch?v=DKfz0skc2oM
~5 min in


Error: RuntimeError: MPS: Unsupported Border padding mode

I've changed the config.yaml to taichi:
https://github.com/Fannovel16/ComfyUI-Frame-Interpolation?tab=readme-ov-file#support-for-non-cuda-device-experimental

I've tried changing the padding mode:
warped = F.grid_sample(image, normalized_flow2, mode='bilinear', padding_mode='zeros', align_corners=False)

Tried this:
pip install --pre torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/cpu





!!! Exception during processing !!!
Traceback (most recent call last):
  File "/Users/NAME/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/NAME/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/NAME/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/NAME/ComfyUI/custom_nodes/ComfyUI-Frame-Interpolation/vfi_models/film/__init__.py", line 88, in vfi
    relust = inference(model, frame_0, frame_1, multiplier - 1)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/NAME/ComfyUI/custom_nodes/ComfyUI-Frame-Interpolation/vfi_models/film/__init__.py", line 36, in inference
    prediction = model(x0, x1, dt)
                 ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/ComfyUI/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/ComfyUI/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/interpolator.py", line 15, in forward
    x1: Tensor,
    batch_dt: Tensor) -> Tensor:
    _0 = (self).debug_forward(x0, x1, batch_dt, )
          ~~~~~~~~~~~~~~~~~~~ <--- HERE
    return (_0["image"])[0]
  def debug_forward(self: __torch__.interpolator.Interpolator,
  File "code/__torch__/interpolator.py", line 29, in debug_forward
    feature_pyramids = [_2, _3]
    predict_flow = self.predict_flow
    forward_residual_flow_pyramid = (predict_flow).forward(feature_pyramids[0], feature_pyramids[1], )
                                     ~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    predict_flow0 = self.predict_flow
    backward_residual_flow_pyramid = (predict_flow0).forward(feature_pyramids[1], feature_pyramids[0], )
  File "code/__torch__/pyramid_flow_estimator.py", line 24, in forward
      level_size = torch.slice(torch.size(feature_pyramid_a[i]), 2, 4)
      v1 = _0(torch.mul(v0, 2), level_size, None, "bilinear", None, None, False, )
      warped = __torch__.util.warp(feature_pyramid_b[i], v1, )
               ~~~~~~~~~~~~~~~~~~~ <--- HERE
      _predictor0 = self._predictor
      v_residual = (_predictor0).forward(feature_pyramid_a[i], warped, )
  File "code/__torch__/util.py", line 78, in warp
  _31 = torch.sub(torch.unsqueeze(_30, 2), torch.select(normalized_flow2, -1, 0))
  normalized_flow20 = torch.stack([_28, _31], 3)
  warped = _20(image, normalized_flow20, "bilinear", "border", False, )
           ~~~ <--- HERE
  _32 = torch.reshape(warped, torch.size(image))
  return _32
  File "code/__torch__/torch/nn/functional.py", line 83, in grid_sample
  else:
    align_corners0 = unchecked_cast(bool, align_corners)
  _12 = torch.grid_sampler(input, grid, mode_enum, padding_mode_enum, align_corners0)
        ~~~~~~~~~~~~~~~~~~ <--- HERE
  return _12

Traceback of TorchScript, original code (most recent call last):
  File "C:\Users\Danylo\PycharmProjects\frame-interpolation-pytorch\interpolator.py", line 160, in forward
    @torch.jit.export
    def forward(self, x0, x1, batch_dt) -> torch.Tensor:
        return self.debug_forward(x0, x1, batch_dt)['image'][0]
               ~~~~~~~~~~~~~~~~~~ <--- HERE
  File "C:\Users\Danylo\PycharmProjects\frame-interpolation-pytorch\interpolator.py", line 109, in debug_forward
    
        # Predict forward flow.
        forward_residual_flow_pyramid = self.predict_flow(feature_pyramids[0], feature_pyramids[1])
                                        ~~~~~~~~~~~~~~~~~ <--- HERE
    
        # Predict backward flow.
  File "C:\Users\Danylo\PycharmProjects\frame-interpolation-pytorch\util.py", line 85, in warp
    ], dim=3)

    warped = F.grid_sample(image, normalized_flow2,
             ~~~~~~~~~~~~~ <--- HERE
                           mode='bilinear', padding_mode='border', align_corners=False)
    return warped.reshape(image.shape)
  File "C:\Users\Danylo\anaconda3\envs\research\lib\site-packages\torch\nn\functional.py", line 4223, in grid_sample
        align_corners = False

    return torch.grid_sampler(input, grid, mode_enum, padding_mode_enum, align_corners)
           ~~~~~~~~~~~~~~~~~~ <--- HERE
RuntimeError: MPS: Unsupported Border padding mode

**Comment by deadcat000** [comment]
Seems to me like someone forgot to use relative paths? "C:\Users\Danylo..." clearly does not exist on a Mac.

**Comment by gioferreira** [comment]
I'm getting the same error on an M1 and M2, clean comfyui install.
Tried with Taichi, Taichi Nightly, the error is always the same:

MPS: Unsupported Border padding mode

Python 3.10

**Comment by tamler** [comment]
I posted an issue on the potential issue: 
[C:\PATH ](https://github.com/dajes/frame-interpolation-pytorch/issues/4)

**Comment by deadcat000** [comment]
For anyone wanting to do frame interpolation on a Mac you could use these old nodes in the meantime https://github.com/melMass/comfy_mtb?tab=readme-ov-file#image-interpolation-animation 
download the FILM models here https://drive.google.com/drive/folders/1q8110-qp225asX3DQvZnfLfJPkCHmDpy
But beware that it will fall back to CPU and be pretty slow.

**Comment by h0x91b** [comment]
I am changed ".../ComfyUI/custom_nodes/ComfyUI-Frame-Interpolation/vfi_models/rife/rife_arch.py" line 63 from "border" to `padding_mode="reflection",` ("zeros" also works)

have no idea what result with `border` should be like, but with `reflection` it's acceptable for me at least...

**Comment by michele-fadda** [comment]
this unfortunately, for FILM rather than RIFE, cannot be solved by editing the custom mode code in Python, as the problem seems to be about the model itself.

**Comment by bigcat88** [comment]
https://github.com/pytorch/pytorch/issues/125098#issuecomment-2270384282

**Comment by karltdev** [comment]
This merge does not fix the FILM issue.

**Comment by cavivie** [comment]
plz reopen the issue, this merge only partially fixes it.

**Comment by cavivie** [comment]
For anyone looking for a solution, the film needs to be fixed in the same way, which requires re-shaping the model.

Please change these codes to patch to fix it:
[ComfyUI-Frame-Interpolation](https://github.com/Fannovel16/ComfyUI-Frame-Interpolation/blob/main/vfi_models/film/film_arch.py#L712-L713)
[frame-interpolation-pytorch](https://github.com/dajes/frame-interpolation-pytorch/blob/main/util.py#L85-L87)

the patch code:
```python
    padding_mode = "border"
    if device.type == "mps":
        # https://github.com/pytorch/pytorch/issues/125098
        padding_mode = "zeros"
        normalized_flow2 = normalized_flow2.clamp(-1, 1)
    warped = F.grid_sample(
        input=image,
        grid=normalized_flow2,
        mode='bilinear',
        padding_mode=padding_mode,
        align_corners=False,
    )
```

**Comment by bigcat88** [comment]
can you create a PR for this?

**Comment by cavivie** [comment]
@bigcat88 Yeah, I have created a [PR](https://github.com/Fannovel16/ComfyUI-Frame-Interpolation/pull/81) for this issue.

**Comment by eisneim** [comment]
## this is my solution:
change util.py change *padding_mode='border'* to *zeros*
```
    warped = F.grid_sample(image, normalized_flow2, mode='bilinear', 
        padding_mode='zeros', align_corners=False)
        # mode='bilinear', padding_mode='border', align_corners=False)
```
then we need to re-export the jit model

``` python
from interpolator import Interpolator
interpolator = Interpolator()
interpolator.eval()

film_model_path = "/original model weights/film_net_fp32.pt"
film_model = torch.jit.load(film_model_path, map_location='cpu')
film_model.eval()
film_model.float()
film_model = film_model.to(DEVICE)

interpolator.load_state_dict(film_model.state_dict())

interpolatorJit = torch.jit.script(interpolator)
interpolatorJit.save("/Users/teli/www/ml/frame_interpolation/frame-interpolation-pytorch-main/pretrained/film_fp32.pt")

interpolatorfp16 = torch.jit.script(interpolator.half())
interpolatorfp16.save("/Users/teli/www/ml/frame_interpolation/frame-interpolation-pytorch-main/pretrained/film_fp16.pt")
```

from now on you can use the new model weights on mac
```
film_model = torch.jit.load("the exported model weight.pt", map_location='cpu')
```

**Comment by gmacgmac** [comment]
Modify this file:
CopyComfyUI/custom_nodes/comfyui-frame-interpolation/vfi_models/rife/rife_arch.py

Update the "def warp" function to this - works perfectly  having to change the YAML
```
def warp(tenInput, tenFlow):
    k = (str(tenFlow.device), str(tenFlow.size()))
    if k not in backwarp_tenGrid:
        tenHorizontal = (
            torch.linspace(-1.0, 1.0, tenFlow.shape[3], device=device)
            .view(1, 1, 1, tenFlow.shape[3])
            .expand(tenFlow.shape[0], -1, tenFlow.shape[2], -1)
        )
        tenVertical = (
            torch.linspace(-1.0, 1.0, tenFlow.shape[2], device=device)
            .view(1, 1, tenFlow.shape[2], 1)
            .expand(tenFlow.shape[0], -1, -1, tenFlow.shape[3])
        )
        backwarp_tenGrid[k] = torch.cat([tenHorizontal, tenVertical], 1).to(device)
    tenFlow = torch.cat(
        [
            tenFlow[:, 0:1, :, :] / ((tenInput.shape[3] - 1.0) / 2.0),
            tenFlow[:, 1:2, :, :] / ((tenInput.shape[2] - 1.0) / 2.0),
        ],
        1,
    )
    g = (backwarp_tenGrid[k] + tenFlow).permute(0, 2, 3, 1)
    if tenInput.type() == "torch.cuda.HalfTensor":
        g = g.half()
        
    # Determine appropriate padding mode based on device
    padding_mode = "border"
    if torch.device(tenInput.device).type == "mps":
        # Fix for MPS backend
        padding_mode = "zeros"
        g = g.clamp(-1, 1)  # Ensure values are in valid range
        
    return torch.nn.functional.grid_sample(
        input=tenInput,
        grid=g,
        mode="bilinear",
        padding_mode=padding_mode,
        align_corners=True,
    )
```

**Comment by bijlevel** [comment]
Could someone please tell me where on my Mac I can find the folder frame-interpolation-pytorch and then the file util.py to fix the issue for FILM. Can't find this on my Mac. I have installed the custom nodes for ComfyUI-Frame-Interpolation and all the vfi models appear and RIFE for instance is working (after changing/fixing the rife_arch.py code). All help much appreciated!

**Comment by bijlevel** [comment]
> [@bijlevel](https://github.com/bijlevel) download from here [frame-interpolation-pytorch](https://github.com/dajes/frame-interpolation-pytorch)

Thanks. I did already discover this download, but is it required to get FILM working in ComfyUI? Because I had ComfyUI install these custom nodes for ComfyUI-Frame-Interpolation and it seems odd if one has to install this frame-interpolation-pytorch just for getting FILM to work, while RIFE does work without it. But if I need it, do I install it in the venv of Pyhton?

**Comment by eisneim** [comment]
@bijlevel  you just need to get the model file converted to support mac Comfy does not need [frame-interpolation-pytorch](https://github.com/dajes/frame-interpolation-pytorch) follow the instruction i posted to get the model file converted then you can use this new model file to work with comfy on Mac

**Comment by bijlevel** [comment]
Sorry for the late reply, but I missed somehow your reply. I'm confused. If you mean by your solution the code change you proposed on Jan 20, then I still need util.py, which will be present, I assume, when frame-interpolation-torch is installed. But you tell me I don't need that, so I assume I just need to alter the code of the file 'film_arch.py' in the same way as the code for RIFE (rife_arch.py) had to be changed to accomodate mps of a Silicon Mac as posted by @cavivie. I did change to code of fil_arch.py, but still got the 'mps border' error. Sorry for my ignorance, but I don't understand why the fix works for RIVE and not for FILM.

**Comment by eisneim** [comment]
@bijlevel i'v converted the model to support Mac, you don't need to change anything, just use my  pretraind FILM model [google drive](https://drive.google.com/file/d/16usfzvVsa0VM2Iy32u1C-C3Rsx8Uz0Lq/view?usp=drive_link) or [百度网盘](https://pan.baidu.com/s/1GPs9ph8JbNQT87eGwUp7rQ?pwd=8pxu) password: 8pxu

**Comment by cavivie** [comment]
> Sorry for the late reply, but I missed somehow your reply. I'm confused. If you mean by your solution the code change you proposed on Jan 20, then I still need util.py, which will be present, I assume, when frame-interpolation-torch is installed. But you tell me I don't need that, so I assume I just need to alter the code of the file 'film_arch.py' in the same way as the code for RIFE (rife_arch.py) had to be changed to accomodate mps of a Silicon Mac as posted by [@cavivie](https://github.com/cavivie). I did change to code of film_arch.py, but still got the 'mps border' error. Sorry for my ignorance, but I don't understand why the fix works for RIVE and not for FILM.

I think you missed an important sentence.
> which requires re-exporting film net models

Run the command in https://github.com/dajes/frame-interpolation-pytorch :
```shell
python export.py "model_path" "save_path" [--statedict] [--fp32] [--skiptest] [--gpu]
```

**Comment by bijlevel** [comment]
@cavivie Thanks for trying to help me out, but as said, I'm still a beginner and I don't understand what you mean by "run the command to export a new film model". I'm able to apply the patch by changing the util.py file but it is unclear to me what to do next.

@eisneim Thank you for making the model file avaible, but unfortunately Google drive needs a consent (probably from you) to access the drive and for the second option I need to install BaiduNetdisk for Mac, which I did, but then, to use this disk, I GUESS I have to make an account, but because all is in Japanese (I assume) I'm totally in the dark about what to do next. So I think I have to wait for your consent to access your Google drive. But if you happen to use Dropbox, that would be more convenient for me.

Thanks both of you anyway for all the help until now!

**Comment by eisneim** [comment]
@bijlevel sorry for that  i've update the google drive

**Comment by bijlevel** [comment]
> [@bijlevel](https://github.com/bijlevel) sorry for that i've update the google drive

Thank you! I have downloaded the file and added it to the 'film' folder inside the 'ckpts' folder of the comfyui-frame-interpolation' folder. BUT this model (film_fp16.pt) does not appear in the ckpt_name list of the FILN VFI node, so I can't choose it. Only the not working film_net_fp32.pt does appear in the list. See screenprint. So I'm at my wits end!

<img width="361" alt="Image" src="https://github.com/user-attachments/assets/6637fb30-b5f2-4510-8b88-28b404c17641" />

**Comment by bijlevel** [comment]
> [@bijlevel](https://github.com/bijlevel) just edit the comfy config file the code to use fp16 file

I did edit ' __init__.py' file in the folder vfi_models/film folder, because that was the only one with reference to the ckpt name. Now the ckpt does appear in the FILMVFI node, but I'm getting a new error: **RuntimeError: Input type (MPSFloatType) and weight type (MPSHalfType) should be the same**  I guess it has to do with using float16 in stead of float32, but I don't see a way to change this.

**Comment by eisneim** [comment]
https://drive.google.com/file/d/1Z0XgtBB66-umEjcmtU4T_4hQ1dg1DQHq/view?usp=sharing fp32

**Comment by bijlevel** [comment]
> https://drive.google.com/file/d/1Z0XgtBB66-umEjcmtU4T_4hQ1dg1DQHq/view?usp=sharing fp32

Finally the FILM node works! @eisneim thank you so much for your help and for providing the right models! Very much appreciated!

BTW since I can now compare the output of FILM and RIVE I have to admit there is not much difference between the both. Also both nodes produce very fast their output, which make me wonder how much they attribute to the quality of the interpolation. Because of my previous "struggles" I also did run the the workflow without RIVE/FILM and again the output is no so much different from the one with RIVE/FILM. But anyway the workflow is now working as it should be, so now I can start finetuning things!. Thanks again!

**Comment by eisneim** [comment]
@bijlevel for fast VFI i prefer [AMT](https://nk-cs-zzl.github.io/projects/amt/index.html) over FILM for high quality but slower VFI i would choose: [MoMo](https://github.com/JHLew/MoMo) or PerVFI

**Comment by fehmi** [comment]
> > https://drive.google.com/file/d/1Z0XgtBB66-umEjcmtU4T_4hQ1dg1DQHq/view?usp=sharing fp32
> 
> Finally the FILM node works! [@eisneim](https://github.com/eisneim) thank you so much for your help and for providing the right models! Very much appreciated!
> 
> BTW since I can now compare the output of FILM and RIVE I have to admit there is not much difference between the both. Also both nodes produce very fast their output, which make me wonder how much they attribute to the quality of the interpolation. Because of my previous "struggles" I also did run the the workflow without RIVE/FILM and again the output is no so much different from the one with RIVE/FILM. But anyway the workflow is now working as it should be, so now I can start finetuning things!. Thanks again!

How did you succeed? I downloaded the fp32 model here and getting "RuntimeError: MPS: Unsupported Border padding mode" error.

**Comment by bijlevel** [comment]
> > > https://drive.google.com/file/d/1Z0XgtBB66-umEjcmtU4T_4hQ1dg1DQHq/view?usp=sharing fp32
> > 
> > 
> > Finally the FILM node works! [@eisneim](https://github.com/eisneim) thank you so much for your help and for providing the right models! Very much appreciated!
> > BTW since I can now compare the output of FILM and RIVE I have to admit there is not much difference between the both. Also both nodes produce very fast their output, which make me wonder how much they attribute to the quality of the interpolation. Because of my previous "struggles" I also did run the the workflow without RIVE/FILM and again the output is no so much different from the one with RIVE/FILM. But anyway the workflow is now working as it should be, so now I can start finetuning things!. Thanks again!
> 
> How did you succeed? I downloaded the fp32 model here and getting "RuntimeError: MPS: Unsupported Border padding mode" error.
For the FILM interpolator you also need to adjust the file film_arch.py:
https://github.com/Fannovel16/ComfyUI-Frame-Interpolation/pull/81/commits/4fdb46e63c23b67f6300c3be0acd9ad84236818c

**Comment by cavivie** [comment]
> How did you succeed? I downloaded the fp32 model here and getting "RuntimeError: MPS: Unsupported Border padding mode" error.

You have to re-export the film models with [the patch](https://github.com/dajes/frame-interpolation-pytorch/pull/6) from [frame-interpolation-pytorch](https://github.com/dajes/frame-interpolation-pytorch), and put thems into ComfyUI models path.
