### ISSUE TITLE
 nvrtc: error: failed to open nvrtc-builtins64_114.dll.

### ISSUE THREAD

**Issue by guahunyo** [Fannovel16/ComfyUI-Frame-Interpolation#49]
![image](https://github.com/Fannovel16/ComfyUI-Frame-Interpolation/assets/18573180/dce0c5f3-5438-4f32-a2a4-173cb5dcbf3d)
![image](https://github.com/Fannovel16/ComfyUI-Frame-Interpolation/assets/18573180/fb255d21-fdb6-4980-8892-95eb7985df1f)

**Comment by Fannovel16** [comment]
Fixed in https://github.com/Fannovel16/ComfyUI-Frame-Interpolation/commit/86b0e54be09ba34453857476ab97eb6ee9bbc03b
