### ISSUE TITLE
Parameter Meanings?

### ISSUE THREAD

**Issue by ckao10301** [Fannovel16/ComfyUI-Frame-Interpolation#53]
Hi, what do each of these parameters do? Can't find an explanation anywhere. Thanks

![image](https://github.com/Fannovel16/ComfyUI-Frame-Interpolation/assets/129625358/5322afb8-3814-440b-a46e-445bdd327d99)

**Comment by Fannovel16** [comment]
`clear_cache_after_n_frames` indicates the amount of frames processed before clearing CUDA cache. This help reducing VRAM usage. The bigger is faster but also more chance of OOM

`multiplier` is roughly how many times larger is the number of output frames compared to input frames? The number of output frames = `n + [(n - 1) × multiplier]` to be exact. 

You don't need to care about other params really
