### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by levaleureux** [Fannovel16/ComfyUI-Frame-Interpolation#6]
Is there anywhere some workflow example to know how to use those nodes?

**Comment by Fannovel16** [comment]
I just updated README with workflow examples

**Comment by levaleureux** [comment]
thanks a lot :)

**Comment by EmmaThompson123** [comment]
@Fannovel16 Could you please share the workflow json like these: https://github.com/PowerHouseMan/ComfyUI-AdvancedLivePortrait/tree/main/sample/workflows ?
