### ISSUE TITLE
Exception during processing!!! Tried all GitHub base urls to download IFUNet.pth but no suceess.

### ISSUE THREAD

**Issue by wang-tianjinjl** [Fannovel16/ComfyUI-Frame-Interpolation#65]
Exception during processing!!! Tried all GitHub base urls to download IFUNet.pth but no suceess.

**Comment by liuenccg** [comment]
error.HTTPError: HTTP Error 404: Not Found

**Comment by botnang** [comment]
same +1

**Comment by Fannovel16** [comment]
@botnang @wang-tianjinjl @liuenccg [VSGAN-tensorrt-docker](https://github.com/styler00dollar/VSGAN-tensorrt-docker) haven't host that file anymore for some reasons so I reuploaded the file to a mirror which is already included in the code

**Comment by botnang** [comment]
> @botnang @wang-tianjinjl @liuenccg [VSGAN-tensorrt-docker](https://github.com/styler00dollar/VSGAN-tensorrt-docker) haven't host that file anymore for some reasons so I reuploaded the file to [a mirror](https://github.com/Fannovel16/ComfyUI-Frame-Interpolation/releases/tag/models) which is already included in the code

a lot thanks:)

**Comment by liuenccg** [comment]
> @botnang @wang-tianjinjl @liuenccg [VSGAN-tensorrt-docker](https://github.com/styler00dollar/VSGAN-tensorrt-docker) haven't host that file anymore for some reasons so I reuploaded the file to [a mirror](https://github.com/Fannovel16/ComfyUI-Frame-Interpolation/releases/tag/models) which is already included in the code

Thank you, may you be happy and joyful every day
