### ISSUE TITLE
download IFRNet_S_Vimeo90K.pth but no suceess

### ISSUE THREAD

**Issue by zhangleyan** [Fannovel16/ComfyUI-Frame-Interpolation#68]
Downloading: "https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/IFRNet_S_Vimeo90K.pth" to E:\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\ckpts\ifrnet\IFRNet_S_Vimeo90K.pth

Failed! Trying another endpoint.
Downloading: "https://github.com/Fannovel16/ComfyUI-Frame-Interpolation/releases/download/models/IFRNet_S_Vimeo90K.pth" to E:\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\ckpts\ifrnet\IFRNet_S_Vimeo90K.pth

Failed! Trying another endpoint.
Downloading: "https://github.com/dajes/frame-interpolation-pytorch/releases/download/v1.0.0/IFRNet_S_Vimeo90K.pth" to E:\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\ckpts\ifrnet\IFRNet_S_Vimeo90K.pth

!!! Exception during processing!!! Tried all GitHub base urls to download IFRNet_S_Vimeo90K.pth but no suceess.

**Comment by haomole** [comment]
dd

**Comment by Fannovel16** [comment]
Ah seems like I have to re-upload all models from VSGAN lol

**Comment by Fannovel16** [comment]
At least uploaded that to mirror https://github.com/Fannovel16/ComfyUI-Frame-Interpolation/releases/
