### ISSUE TITLE
Do you see that as an interpolation node?

### ISSUE THREAD

**Issue by ManuelMultiverse** [Fannovel16/ComfyUI-Frame-Interpolation#9]
https://openaccess.thecvf.com/content/ICCV2023/papers/Siyao_Deep_Geometrized_Cartoon_Line_Inbetweening_ICCV_2023_paper.pdf

**Comment by Fannovel16** [comment]
Yes ofc 👍. But here is the problem. Their [implementation](https://github.com/lisiyao21/AnimeInbet) doesn't release the script to preprocess raster lineart images to "vector graphs" (including `vertex location` and `connection`). That means it currently can only run on their dataset so it is impossible to make a node.

I know some detail about vector graphs tho. It is just another way of saying "vectorization" (convert raster lineart image into svg, but you save the result in their json format). In the paper, they use https://github.com/MarkMoHR/virtual_sketching to vectorize frames. I don't have enough interest or time irl to implement the preprocessor. If you can make it, please share the script to https://github.com/lisiyao21/AnimeInbet/issues/7

**Comment by ManuelMultiverse** [comment]
Okey, thanks! ill find a way to try to code that!
